# @generated by python.gen (pGenie). DO NOT EDIT.
# SPDX-FileCopyrightText: 2026 Viacheslav Shvets
# SPDX-License-Identifier: MIT-0

from enum import StrEnum
from typing import cast


class Mood(StrEnum):
    HAPPY = "happy"
    SAD = "sad"
    MEH = "meh"

    @staticmethod
    def _decode(src: object) -> "Mood":
        return Mood(cast(str, src))

    def _encode(self) -> "Mood":
        return self
