# @generated by python.gen (pGenie). DO NOT EDIT.
# SPDX-FileCopyrightText: 2026 Viacheslav Shvets
# SPDX-License-Identifier: MIT-0

from dataclasses import dataclass
from typing import cast


@dataclass(frozen=True, slots=True)
class Point2D:
    """Decoding/encoding this composite requires register_types(conn) first.

    Without per-connection registration psycopg returns the value as a
    raw string, which the generated _decode cannot splat into the dataclass.
    """

    x: float | None
    y: float | None

    @staticmethod
    def _decode(src: object) -> "Point2D":
        return Point2D(*cast(tuple[float | None, float | None], src))

    def _encode(self) -> tuple[float | None, float | None]:
        return (self.x, self.y)
