# @generated by python.gen (pGenie). DO NOT EDIT.
# SPDX-FileCopyrightText: 2026 Viacheslav Shvets
# SPDX-License-Identifier: MIT-0

from __future__ import annotations

from collections.abc import Mapping
from dataclasses import dataclass
from datetime import date, datetime
from decimal import Decimal
from typing import cast
from uuid import UUID

from ._core import JsonValue
from ._core import require_array
from .types.mood import Mood
from .types.point_2_d import Point2D
from .types.tag_value import TagValue
from .types.mood import Mood
from .types.mood import Mood
from .types.point_2_d import Point2D
from .types.tag_value import TagValue
from .types.mood import Mood
from .types.point_2_d import Point2D
from .types.mood import Mood
from .types.mood import Mood
from .types.mood import Mood


@dataclass(frozen=True, slots=True)
class GetSpecimenRow:
    id: int
    pub_id: UUID
    flag: bool
    small: int
    medium: int
    large: int
    ratio: float
    precise: float
    title: str
    code: str
    letter: str
    born_on: date
    created_at: datetime
    amount: Decimal
    blob: bytes
    doc_json: JsonValue
    doc_jsonb: JsonValue
    maybe_text: str | None
    maybe_int: int | None
    maybe_uuid: UUID | None
    maybe_ts: datetime | None
    maybe_num: Decimal | None
    tags: list[str | None]
    related_ids: list[UUID | None] | None
    grid: list[int | None] | None
    feeling: Mood
    origin: Point2D | None
    label: str
    rev: int
    meta: JsonValue


def decode_get_specimen(row: Mapping[str, object]) -> GetSpecimenRow:
    return GetSpecimenRow(
        id=cast(int, row["id"]),
        pub_id=cast(UUID, row["pub_id"]),
        flag=cast(bool, row["flag"]),
        small=cast(int, row["small"]),
        medium=cast(int, row["medium"]),
        large=cast(int, row["large"]),
        ratio=cast(float, row["ratio"]),
        precise=cast(float, row["precise"]),
        title=cast(str, row["title"]),
        code=cast(str, row["code"]),
        letter=cast(str, row["letter"]),
        born_on=cast(date, row["born_on"]),
        created_at=cast(datetime, row["created_at"]),
        amount=cast(Decimal, row["amount"]),
        blob=cast(bytes, row["blob"]),
        doc_json=cast(JsonValue, row["doc_json"]),
        doc_jsonb=cast(JsonValue, row["doc_jsonb"]),
        maybe_text=cast(str | None, row["maybe_text"]),
        maybe_int=cast(int | None, row["maybe_int"]),
        maybe_uuid=cast(UUID | None, row["maybe_uuid"]),
        maybe_ts=cast(datetime | None, row["maybe_ts"]),
        maybe_num=cast(Decimal | None, row["maybe_num"]),
        tags=cast(list[str | None], row["tags"]),
        related_ids=cast(list[UUID | None] | None, row["related_ids"]),
        grid=cast(list[int | None] | None, row["grid"]),
        feeling=Mood._decode(row["feeling"]),
        origin=None if row["origin"] is None else Point2D._decode(row["origin"]),
        label=cast(str, row["label"]),
        rev=cast(int, row["rev"]),
        meta=cast(JsonValue, row["meta"]),
    )


@dataclass(frozen=True, slots=True)
class GetTaggedItemRow:
    id: int
    name: str
    tag: TagValue


def decode_get_tagged_item(row: Mapping[str, object]) -> GetTaggedItemRow:
    return GetTaggedItemRow(
        id=cast(int, row["id"]),
        name=cast(str, row["name"]),
        tag=TagValue._decode(row["tag"]),
    )


@dataclass(frozen=True, slots=True)
class InsertSpecimenRow:
    id: int
    pub_id: UUID
    flag: bool
    small: int
    medium: int
    large: int
    ratio: float
    precise: float
    title: str
    code: str
    letter: str
    born_on: date
    created_at: datetime
    amount: Decimal
    blob: bytes
    doc_json: JsonValue
    doc_jsonb: JsonValue
    maybe_text: str | None
    maybe_int: int | None
    maybe_uuid: UUID | None
    maybe_ts: datetime | None
    maybe_num: Decimal | None
    tags: list[str | None]
    related_ids: list[UUID | None] | None
    grid: list[int | None] | None
    feeling: Mood
    moods: list[Mood | None] | None
    origin: Point2D | None
    label: str
    rev: int
    meta: JsonValue


def decode_insert_specimen(row: Mapping[str, object]) -> InsertSpecimenRow:
    return InsertSpecimenRow(
        id=cast(int, row["id"]),
        pub_id=cast(UUID, row["pub_id"]),
        flag=cast(bool, row["flag"]),
        small=cast(int, row["small"]),
        medium=cast(int, row["medium"]),
        large=cast(int, row["large"]),
        ratio=cast(float, row["ratio"]),
        precise=cast(float, row["precise"]),
        title=cast(str, row["title"]),
        code=cast(str, row["code"]),
        letter=cast(str, row["letter"]),
        born_on=cast(date, row["born_on"]),
        created_at=cast(datetime, row["created_at"]),
        amount=cast(Decimal, row["amount"]),
        blob=cast(bytes, row["blob"]),
        doc_json=cast(JsonValue, row["doc_json"]),
        doc_jsonb=cast(JsonValue, row["doc_jsonb"]),
        maybe_text=cast(str | None, row["maybe_text"]),
        maybe_int=cast(int | None, row["maybe_int"]),
        maybe_uuid=cast(UUID | None, row["maybe_uuid"]),
        maybe_ts=cast(datetime | None, row["maybe_ts"]),
        maybe_num=cast(Decimal | None, row["maybe_num"]),
        tags=cast(list[str | None], row["tags"]),
        related_ids=cast(list[UUID | None] | None, row["related_ids"]),
        grid=cast(list[int | None] | None, row["grid"]),
        feeling=Mood._decode(row["feeling"]),
        moods=None if row["moods"] is None else [None if v is None else Mood._decode(v) for v in cast(list[str | None], require_array(row["moods"]))],
        origin=None if row["origin"] is None else Point2D._decode(row["origin"]),
        label=cast(str, row["label"]),
        rev=cast(int, row["rev"]),
        meta=cast(JsonValue, row["meta"]),
    )


@dataclass(frozen=True, slots=True)
class InsertTaggedItemRow:
    id: int
    name: str
    tag: TagValue


def decode_insert_tagged_item(row: Mapping[str, object]) -> InsertTaggedItemRow:
    return InsertTaggedItemRow(
        id=cast(int, row["id"]),
        name=cast(str, row["name"]),
        tag=TagValue._decode(row["tag"]),
    )


@dataclass(frozen=True, slots=True)
class ListSpecimensByClassRow:
    id: int
    title: str


def decode_list_specimens_by_class(row: Mapping[str, object]) -> ListSpecimensByClassRow:
    return ListSpecimensByClassRow(
        id=cast(int, row["id"]),
        title=cast(str, row["title"]),
    )


@dataclass(frozen=True, slots=True)
class ListSpecimensByFeelingRow:
    id: int
    pub_id: UUID
    feeling: Mood
    title: str
    label: str
    rev: int
    origin: Point2D | None
    tags: list[str | None]
    meta: JsonValue


def decode_list_specimens_by_feeling(row: Mapping[str, object]) -> ListSpecimensByFeelingRow:
    return ListSpecimensByFeelingRow(
        id=cast(int, row["id"]),
        pub_id=cast(UUID, row["pub_id"]),
        feeling=Mood._decode(row["feeling"]),
        title=cast(str, row["title"]),
        label=cast(str, row["label"]),
        rev=cast(int, row["rev"]),
        origin=None if row["origin"] is None else Point2D._decode(row["origin"]),
        tags=cast(list[str | None], row["tags"]),
        meta=cast(JsonValue, row["meta"]),
    )


@dataclass(frozen=True, slots=True)
class ListSpecimensByIdsRow:
    id: int
    pub_id: UUID
    feeling: Mood
    title: str


def decode_list_specimens_by_ids(row: Mapping[str, object]) -> ListSpecimensByIdsRow:
    return ListSpecimensByIdsRow(
        id=cast(int, row["id"]),
        pub_id=cast(UUID, row["pub_id"]),
        feeling=Mood._decode(row["feeling"]),
        title=cast(str, row["title"]),
    )


@dataclass(frozen=True, slots=True)
class ListSpecimensByMoodsRow:
    id: int
    pub_id: UUID
    feeling: Mood
    moods: list[Mood | None] | None
    title: str


def decode_list_specimens_by_moods(row: Mapping[str, object]) -> ListSpecimensByMoodsRow:
    return ListSpecimensByMoodsRow(
        id=cast(int, row["id"]),
        pub_id=cast(UUID, row["pub_id"]),
        feeling=Mood._decode(row["feeling"]),
        moods=None if row["moods"] is None else [None if v is None else Mood._decode(v) for v in cast(list[str | None], require_array(row["moods"]))],
        title=cast(str, row["title"]),
    )


@dataclass(frozen=True, slots=True)
class ListSpecimensKeywordColumnRow:
    id: int
    class_: str


def decode_list_specimens_keyword_column(row: Mapping[str, object]) -> ListSpecimensKeywordColumnRow:
    return ListSpecimensKeywordColumnRow(
        id=cast(int, row["id"]),
        class_=cast(str, row["class"]),
    )


@dataclass(frozen=True, slots=True)
class SearchSpecimensRow:
    id: int
    title: str
    label: str
    meta: JsonValue


def decode_search_specimens(row: Mapping[str, object]) -> SearchSpecimensRow:
    return SearchSpecimensRow(
        id=cast(int, row["id"]),
        title=cast(str, row["title"]),
        label=cast(str, row["label"]),
        meta=cast(JsonValue, row["meta"]),
    )
