from __future__ import annotations

import subprocess
from pathlib import Path

from tests._generated_quality import generated_line_length_issues

REPO_ROOT = Path(__file__).resolve().parents[1]
RUFF_CONFIG = REPO_ROOT / "pyproject.toml"
GENERATED_MARKER = "# @generated by python.gen (pGenie); regeneration overwrites manual changes."


def _generated_python(root: Path) -> list[Path]:
    return sorted(root.rglob("*.py"))


def test_fresh_generated_python_passes_ruff(full_package: Path) -> None:
    generated_src = full_package / "src"
    for command in (("check",), ("format", "--check")):
        result = subprocess.run(
            ["ruff", *command, "--config", str(RUFF_CONFIG), str(generated_src)],
            capture_output=True,
            text=True,
        )
        assert result.returncode == 0, f"ruff {' '.join(command)} failed:\n{result.stdout}{result.stderr}"


def test_fresh_generated_python_has_exact_marker_and_bounded_authored_lines(full_package: Path) -> None:
    paths = _generated_python(full_package / "src")
    assert paths, "fresh generation produced no Python files"

    authored = []
    for path in paths:
        assert path.read_text().splitlines()[0] == GENERATED_MARKER
        path_authored, _ = generated_line_length_issues(path)
        authored.extend(path_authored)

    assert not authored, "generated authored lines exceed 120 characters:\n" + "\n".join(
        issue.label() for issue in authored
    )


def test_line_length_helper_excludes_only_module_sql_token_interiors(tmp_path: Path) -> None:
    path = tmp_path / "sample.py"
    sql_body = "S" * 121
    other_body = "O" * 121
    python_value = "P" * 121
    _ = path.write_text(f'SQL = """\\\n{sql_body}\n"""\nOTHER = """\\\n{other_body}\n"""\nvalue = {python_value!r}\n')

    authored, sql = generated_line_length_issues(path)

    assert [issue.line_number for issue in sql] == [2]
    assert [issue.line_number for issue in authored] == [5, 7]
