from __future__ import annotations

import ast
import asyncio
import importlib
import inspect
import sys
from collections.abc import Callable, Iterator
from contextlib import contextmanager
from datetime import date
from decimal import Decimal
from pathlib import Path
from types import ModuleType

import psycopg

from tests._generated_quality import generated_line_length_issues
from tests._harness import FIXTURE_PROJECT

PACKAGE = Path("src/specimen_client")
STATEMENTS = frozenset(
    {
        "bump_specimen_revision",
        "get_specimen",
        "get_tagged_item",
        "insert_specimen",
        "insert_tagged_item",
        "list_specimens_by_class",
        "list_specimens_by_feeling",
        "list_specimens_by_ids",
        "list_specimens_by_moods",
        "list_specimens_keyword_column",
        "search_specimens",
    }
)
ROWS = {
    "get_specimen": "GetSpecimenRow",
    "get_tagged_item": "GetTaggedItemRow",
    "insert_specimen": "InsertSpecimenRow",
    "insert_tagged_item": "InsertTaggedItemRow",
    "list_specimens_by_class": "ListSpecimensByClassRow",
    "list_specimens_by_feeling": "ListSpecimensByFeelingRow",
    "list_specimens_by_ids": "ListSpecimensByIdsRow",
    "list_specimens_by_moods": "ListSpecimensByMoodsRow",
    "list_specimens_keyword_column": "ListSpecimensKeywordColumnRow",
    "search_specimens": "SearchSpecimensRow",
}
CUSTOM_MODULES = {
    "ACodecWrapper": "a_codec_wrapper",
    "Mood": "mood",
    "Point2D": "point_2_d",
    "TagValue": "tag_value",
    "ZCodecPayload": "z_codec_payload",
}
CORE_TYPES = ("JsonValue", "NoRowError")
MARKER = "# @generated by python.gen (pGenie); regeneration overwrites manual changes."
SPDX = (
    "# SPDX-FileCopyrightText: 2026 Viacheslav Shvets",
    "# SPDX-License-Identifier: MIT-0",
)


def _generated_package(generated_tree: Path) -> Path:
    return generated_tree / PACKAGE


def _python_paths(generated_tree: Path) -> list[Path]:
    return sorted(_generated_package(generated_tree).rglob("*.py"))


def _statement_paths(generated_tree: Path) -> dict[str, Path]:
    statements = _generated_package(generated_tree) / "_generated" / "statements"
    return {path.stem: path for path in statements.glob("*.py") if path.name != "__init__.py"}


def _parse(path: Path) -> ast.Module:
    return ast.parse(path.read_text(), filename=str(path))


def _sql_assignments(tree: ast.Module) -> list[ast.expr]:
    assignments: list[ast.expr] = []
    for node in tree.body:
        if isinstance(node, ast.Assign):
            if any(isinstance(target, ast.Name) and target.id == "SQL" for target in node.targets):
                assignments.append(node.value)
        elif (
            isinstance(node, ast.AnnAssign)
            and isinstance(node.target, ast.Name)
            and node.target.id == "SQL"
            and node.value is not None
        ):
            assignments.append(node.value)
    return assignments


def _top_function(tree: ast.Module, name: str) -> ast.FunctionDef | ast.AsyncFunctionDef:
    matches = [
        node for node in tree.body if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)) and node.name == name
    ]
    assert len(matches) == 1, f"expected one top-level function {name}, found {len(matches)}"
    return matches[0]


def _call_leaf(call: ast.Call) -> str | None:
    if isinstance(call.func, ast.Name):
        return call.func.id
    if isinstance(call.func, ast.Attribute):
        return call.func.attr
    return None


def _args_row_calls(node: ast.AST) -> list[ast.Call]:
    return [
        child
        for child in ast.walk(node)
        if isinstance(child, ast.Call) and isinstance(child.func, ast.Name) and child.func.id == "_args_row"
    ]


def _annotations(tree: ast.Module) -> Iterator[ast.expr]:
    for node in ast.walk(tree):
        if isinstance(node, (ast.arg, ast.AnnAssign)) and node.annotation is not None:
            yield node.annotation
        elif isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)) and node.returns is not None:
            yield node.returns


def _remove_client_modules() -> None:
    for name in list(sys.modules):
        if name == "specimen_client" or name.startswith("specimen_client."):
            del sys.modules[name]


@contextmanager
def _client_modules(
    full_package: Path,
) -> Iterator[tuple[ModuleType, ModuleType, Callable[[str], ModuleType]]]:
    original_path = sys.path.copy()
    previous = {
        name: module
        for name, module in sys.modules.items()
        if name == "specimen_client" or name.startswith("specimen_client.")
    }
    sys.path.insert(0, str(full_package / "src"))
    _remove_client_modules()
    try:
        root = importlib.import_module("specimen_client")
        sync = importlib.import_module("specimen_client.sync")
        yield root, sync, importlib.import_module
    finally:
        _remove_client_modules()
        sys.modules.update(previous)
        sys.path[:] = original_path


def _apply_migrations(db_url: str) -> None:
    migrations = sorted((FIXTURE_PROJECT / "migrations").glob("*.sql"), key=lambda path: int(path.stem))
    assert migrations, "fixture migrations are required for the registration canary"
    with psycopg.connect(db_url, autocommit=True) as conn:
        for migration in migrations:
            _ = conn.execute(migration.read_text().encode())


def test_canonical_fresh_tree(generated_tree: Path) -> None:
    generated_src = generated_tree / "src"
    packages = sorted(path.name for path in generated_src.iterdir() if path.is_dir())
    assert packages == ["specimen_client"]

    package = _generated_package(generated_tree)
    generated = package / "_generated"
    assert set(_statement_paths(generated_tree)) == STATEMENTS
    assert (package / "__init__.py").is_file()
    assert (package / "sync" / "__init__.py").is_file()
    assert [path.relative_to(package) for path in package.rglob("_register.py")] == [Path("_generated/_register.py")]
    assert [path.relative_to(package) for path in package.rglob("types") if path.is_dir()] == [Path("_generated/types")]

    sync_generated = generated / "sync"
    for relative in (Path("statements"), Path("types"), Path("_register.py")):
        assert not (sync_generated / relative).exists()
    assert not list(generated_tree.rglob("golden_sync"))
    assert not list(package.rglob("_rows.py"))


def test_statement_ast_contract(generated_tree: Path) -> None:
    paths = _statement_paths(generated_tree)
    assert set(paths) == STATEMENTS

    for stem in sorted(STATEMENTS):
        tree = _parse(paths[stem])
        sql = _sql_assignments(tree)
        assert len(sql) == 1
        assert isinstance(sql[0], ast.Constant) and isinstance(sql[0].value, str)

        async_function = _top_function(tree, stem)
        sync_function = _top_function(tree, f"{stem}_sync")
        assert isinstance(async_function, ast.AsyncFunctionDef)
        assert isinstance(sync_function, ast.FunctionDef)

        expected_row = ROWS.get(stem)
        row_classes = [node for node in tree.body if isinstance(node, ast.ClassDef) and node.name.endswith("Row")]
        assert [node.name for node in row_classes] == ([] if expected_row is None else [expected_row])

        imports = [
            alias
            for node in tree.body
            if isinstance(node, ast.ImportFrom) and node.module == "psycopg.rows" and node.level == 0
            for alias in node.names
            if alias.name == "args_row" and alias.asname == "_args_row"
        ]
        expected_count = int(expected_row is not None)
        assert len(imports) == expected_count
        if expected_row is None:
            assert not _args_row_calls(tree)
            continue

        row_class = row_classes[0]
        assert len(row_class.decorator_list) == 1
        decorator = row_class.decorator_list[0]
        assert isinstance(decorator, ast.Call) and isinstance(decorator.func, ast.Name)
        assert decorator.func.id == "dataclass" and not decorator.args
        assert {keyword.arg: ast.literal_eval(keyword.value) for keyword in decorator.keywords} == {
            "frozen": True,
            "slots": True,
        }

        for function in (async_function, sync_function):
            calls = _args_row_calls(function)
            assert len(calls) == 1
            assert len(calls[0].args) == 1 and not calls[0].keywords
            assert isinstance(calls[0].args[0], ast.Name) and calls[0].args[0].id == expected_row
            returns = [node for node in function.body if isinstance(node, ast.Return)]
            assert len(returns) == 1 and returns[0].value is not None
            returned = returns[0].value.value if isinstance(returns[0].value, ast.Await) else returns[0].value
            assert isinstance(returned, ast.Call) and calls[0] in returned.args


def test_adapter_strategy_ast_contract(generated_tree: Path) -> None:
    forbidden_functions = {"_decode_row", "pg_decode", "pg_encode", "_cast", "model_dump", "model_validate"}
    forbidden_calls = forbidden_functions | {"cast", "parse_obj"}

    for path in _python_paths(generated_tree):
        tree = _parse(path)
        for node in ast.walk(tree):
            if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
                assert node.name not in forbidden_functions and not node.name.startswith("decode_")
            elif isinstance(node, ast.Call):
                leaf = _call_leaf(node)
                assert leaf not in forbidden_calls and not (leaf or "").startswith("decode_")
            elif isinstance(node, ast.ImportFrom) and node.module == "typing":
                assert all(alias.name != "cast" for alias in node.names)

    for stem, path in _statement_paths(generated_tree).items():
        tree = _parse(path)
        row_imports = [
            (alias.name, alias.asname)
            for node in tree.body
            if isinstance(node, ast.ImportFrom) and node.module == "psycopg.rows" and node.level == 0
            for alias in node.names
        ]
        assert row_imports == ([] if stem == "bump_specimen_revision" else [("args_row", "_args_row")])

        custom_references = [
            node
            for annotation in _annotations(tree)
            for node in ast.walk(annotation)
            if isinstance(node, ast.Attribute)
            and isinstance(node.value, ast.Name)
            and node.value.id == "_db_types"
            and node.attr in CUSTOM_MODULES
        ]
        bare_custom = [
            node
            for annotation in _annotations(tree)
            for node in ast.walk(annotation)
            if isinstance(node, ast.Name) and node.id in CUSTOM_MODULES
        ]
        assert not bare_custom

        namespace_imports = [
            alias
            for node in tree.body
            if isinstance(node, ast.ImportFrom) and node.level == 2 and node.module is None
            for alias in node.names
            if alias.name == "types" and alias.asname == "_db_types"
        ]
        assert len(namespace_imports) == int(bool(custom_references))
        direct_leaf_imports = [
            node
            for node in tree.body
            if isinstance(node, ast.ImportFrom)
            and node.level > 0
            and (node.module == "types" or (node.module or "").startswith("types."))
        ]
        assert not direct_leaf_imports


def test_public_facade_identities_and_signatures(full_package: Path) -> None:
    with _client_modules(full_package) as (root, sync, import_module):
        assert root.sync is sync
        for stem in sorted(STATEMENTS):
            statement = import_module(f"specimen_client._generated.statements.{stem}")
            async_function = getattr(root, stem)
            sync_function = getattr(sync, stem)
            assert async_function is getattr(statement, stem)
            assert sync_function is getattr(statement, f"{stem}_sync")
            assert inspect.iscoroutinefunction(async_function)
            assert not inspect.iscoroutinefunction(sync_function)

            async_signature = inspect.signature(async_function)
            sync_signature = inspect.signature(sync_function)
            assert async_signature.return_annotation == sync_signature.return_annotation
            async_parameters = list(async_signature.parameters.values())
            sync_parameters = list(sync_signature.parameters.values())
            assert len(async_parameters) == len(sync_parameters)
            for index, (async_parameter, sync_parameter) in enumerate(
                zip(async_parameters, sync_parameters, strict=True)
            ):
                assert async_parameter.name == sync_parameter.name
                assert async_parameter.kind == sync_parameter.kind
                assert async_parameter.default == sync_parameter.default
                if index == 0:
                    assert async_parameter.annotation == "AsyncConnection[object]"
                    assert sync_parameter.annotation == "Connection[object]"
                else:
                    assert async_parameter.annotation == sync_parameter.annotation

            row_name = ROWS.get(stem)
            if row_name is not None:
                canonical_row = getattr(statement, row_name)
                assert getattr(root, row_name) is canonical_row
                assert getattr(sync, row_name) is canonical_row

        core = import_module("specimen_client._generated._core")
        for name in CORE_TYPES:
            assert getattr(root, name) is getattr(sync, name) is getattr(core, name)
        for name, leaf in CUSTOM_MODULES.items():
            module = import_module(f"specimen_client._generated.types.{leaf}")
            assert getattr(root, name) is getattr(sync, name) is getattr(module, name)


def test_generated_import_allowlist(generated_tree: Path) -> None:
    allowed_roots = sys.stdlib_module_names | {"__future__", "psycopg", "specimen_client"}
    violations: list[str] = []

    for path in _python_paths(generated_tree):
        tree = _parse(path)
        importlib_aliases: set[str] = set()
        import_module_aliases: set[str] = set()
        for node in ast.walk(tree):
            if isinstance(node, ast.Import):
                for alias in node.names:
                    root = alias.name.partition(".")[0]
                    if root not in allowed_roots:
                        violations.append(f"{path}: absolute import {alias.name}")
                    if alias.name == "importlib":
                        importlib_aliases.add(alias.asname or alias.name)
            elif isinstance(node, ast.ImportFrom) and node.level == 0:
                root = (node.module or "").partition(".")[0]
                if root not in allowed_roots:
                    violations.append(f"{path}: absolute import from {node.module}")
                if node.module == "importlib":
                    import_module_aliases.update(
                        alias.asname or alias.name for alias in node.names if alias.name == "import_module"
                    )

        for node in ast.walk(tree):
            if not isinstance(node, ast.Call):
                continue
            if isinstance(node.func, ast.Name) and node.func.id == "__import__":
                violations.append(f"{path}:{node.lineno}: dynamic __import__")
            if isinstance(node.func, ast.Name) and node.func.id in import_module_aliases:
                violations.append(f"{path}:{node.lineno}: dynamic import_module")
            if (
                isinstance(node.func, ast.Attribute)
                and node.func.attr == "import_module"
                and isinstance(node.func.value, ast.Name)
                and node.func.value.id in importlib_aliases
            ):
                violations.append(f"{path}:{node.lineno}: dynamic importlib.import_module")

    assert not violations, "generated import boundary violations:\n" + "\n".join(violations)


def test_registration_static_and_api_contract(generated_tree: Path, full_package: Path) -> None:
    package = _generated_package(generated_tree)
    register_path = package / "_generated" / "_register.py"
    assert list(package.rglob("_register.py")) == [register_path]
    assert not (package / "_generated" / "sync" / "_register.py").exists()

    tree = _parse(register_path)
    metadata: dict[str, str] = {}
    callback_types: list[str] = []
    for node in tree.body:
        if isinstance(node, ast.Assign) and len(node.targets) == 1:
            target = node.targets[0]
            if isinstance(target, ast.Name) and target.id.endswith("_pg_name"):
                assert isinstance(node.value, ast.Constant) and isinstance(node.value.value, str)
                metadata[target.id] = node.value.value
            if (
                isinstance(node.value, ast.Call)
                and isinstance(node.value.func, ast.Name)
                and node.value.func.id == "_dataclass_callbacks"
            ):
                argument = node.value.args[0]
                assert isinstance(argument, ast.Attribute) and isinstance(argument.value, ast.Name)
                assert argument.value.id == "_db_types"
                callback_types.append(argument.attr)

    assert metadata == {
        "_mood_pg_name": "public.mood",
        "_point_2_d_pg_name": "public.point2d",
        "_tag_value_pg_name": "public.tag_value",
        "_z_codec_payload_pg_name": "public.z_codec_payload",
        "_a_codec_wrapper_pg_name": "public.a_codec_wrapper",
    }
    assert callback_types == ["Point2D", "TagValue", "ZCodecPayload", "ACodecWrapper"]

    async_register = _top_function(tree, "register_types")
    sync_register = _top_function(tree, "register_types_sync")
    assert isinstance(async_register, ast.AsyncFunctionDef)
    assert isinstance(sync_register, ast.FunctionDef)
    expected_fetch_order = [
        "_mood_pg_name",
        "_point_2_d_pg_name",
        "_tag_value_pg_name",
        "_z_codec_payload_pg_name",
        "_a_codec_wrapper_pg_name",
    ]
    for function in (async_register, sync_register):
        fetch_calls = sorted(
            (
                node
                for node in ast.walk(function)
                if isinstance(node, ast.Call) and isinstance(node.func, ast.Attribute) and node.func.attr == "fetch"
            ),
            key=lambda node: node.lineno,
        )
        fetch_metadata = [
            call.args[1].id for call in fetch_calls if len(call.args) == 2 and isinstance(call.args[1], ast.Name)
        ]
        assert fetch_metadata == expected_fetch_order

    with _client_modules(full_package) as (root, sync, import_module):
        register = import_module("specimen_client._generated._register")
        assert root.register_types is register.register_types
        assert sync.register_types is register.register_types_sync
        assert "register_types" in root.__all__
        assert "register_types" in sync.__all__
        assert inspect.iscoroutinefunction(root.register_types)
        assert not inspect.iscoroutinefunction(sync.register_types)


def test_registration_roundtrip_two_surfaces(full_package: Path, roundtrip_db: str) -> None:
    _apply_migrations(roundtrip_db)
    with _client_modules(full_package) as (root, sync, _):

        async def write_and_read() -> tuple[int, int, int]:
            conn = await psycopg.AsyncConnection.connect(roundtrip_db, autocommit=True)
            try:
                await root.register_types(conn)
                tagged = await root.insert_tagged_item(
                    conn,
                    name="takeover-tag",
                    tag=root.TagValue(value="blue"),
                )
                tagged_hit = await root.get_tagged_item(conn, id=tagged.id)
                assert type(tagged) is root.InsertTaggedItemRow
                assert type(tagged_hit) is root.GetTaggedItemRow
                assert type(tagged_hit.tag) is root.TagValue

                payload = root.ZCodecPayload(class_=71, pg_decode="takeover", pg_encode=None)
                wrapper = root.ACodecWrapper(
                    payload=root.ZCodecPayload(class_=72, pg_decode="nested", pg_encode=None),
                    feeling=root.Mood.SAD,
                    note="canary",
                )
                specimen = await root.insert_specimen(
                    conn,
                    doc_jsonb={"contract": "takeover"},
                    feeling=root.Mood.HAPPY,
                    origin=root.Point2D(x=3.0, y=4.0),
                    flag=True,
                    small=1,
                    medium=2,
                    large=3,
                    ratio=0.5,
                    precise=0.25,
                    title="takeover-specimen",
                    code="T-1",
                    letter="t",
                    born_on=date(2026, 7, 13),
                    amount=Decimal("7.13"),
                    blob=b"takeover",
                    doc_json=["canary"],
                    maybe_text=None,
                    maybe_int=None,
                    maybe_uuid=None,
                    maybe_ts=None,
                    maybe_num=None,
                    tags=["contract"],
                    related_ids=None,
                    grid=None,
                    moods=[root.Mood.HAPPY, None],
                    codec_payload=payload,
                    codec_payloads=[payload],
                    codec_wrapper=wrapper,
                )
                specimen_hit = await root.get_specimen(conn, id=specimen.id)
                assert type(specimen) is root.InsertSpecimenRow
                assert type(specimen_hit) is root.GetSpecimenRow
                assert type(specimen_hit.codec_payload) is root.ZCodecPayload
                assert type(specimen_hit.codec_wrapper) is root.ACodecWrapper
                assert type(specimen_hit.codec_wrapper.payload) is root.ZCodecPayload
                return tagged.id, specimen.id, conn.info.backend_pid
            finally:
                await conn.close()

        tagged_id, specimen_id, async_backend_pid = asyncio.run(write_and_read())
        with psycopg.connect(roundtrip_db, autocommit=True) as conn:
            assert conn.info.backend_pid != async_backend_pid
            sync.register_types(conn)
            tagged_hit = sync.get_tagged_item(conn, id=tagged_id)
            specimen_hit = sync.get_specimen(conn, id=specimen_id)
            assert type(tagged_hit) is sync.GetTaggedItemRow is root.GetTaggedItemRow
            assert type(tagged_hit.tag) is sync.TagValue is root.TagValue
            assert type(specimen_hit) is sync.GetSpecimenRow is root.GetSpecimenRow
            assert type(specimen_hit.codec_wrapper) is sync.ACodecWrapper is root.ACodecWrapper
            assert type(specimen_hit.codec_wrapper.payload) is sync.ZCodecPayload is root.ZCodecPayload


def test_fresh_output_h2_budget(generated_tree: Path) -> None:
    paths = _python_paths(generated_tree)
    statement_paths = _statement_paths(generated_tree)
    sql_count = sum(len(_sql_assignments(_parse(path))) for path in statement_paths.values())
    metrics = {
        "python_files": len(paths),
        "total_lines": sum(len(path.read_text().splitlines()) for path in paths),
        "statement_modules": len(statement_paths),
        "statement_lines": sum(len(path.read_text().splitlines()) for path in statement_paths.values()),
        "sql_assignments": sql_count,
    }

    assert metrics["python_files"] <= 26, metrics
    assert metrics["total_lines"] <= 1500, metrics
    assert metrics["statement_modules"] == 11, metrics
    assert metrics["statement_lines"] <= 900, metrics
    assert metrics["sql_assignments"] == 11, metrics
    assert set(statement_paths) == STATEMENTS
    assert not (_generated_package(generated_tree) / "_generated" / "sync" / "statements").exists()


def test_generated_file_quality_and_required_generator(generated_tree: Path) -> None:
    paths = _python_paths(generated_tree)
    authored = []
    sql = []
    for path in paths:
        lines = path.read_text().splitlines()
        assert lines[:3] == [MARKER, *SPDX]
        path_authored, path_sql = generated_line_length_issues(path)
        authored.extend(path_authored)
        sql.extend(path_sql)

    assert not authored, "authored generated lines exceed 120 characters:\n" + "\n".join(
        issue.label() for issue in authored
    )
    assert not sql, "SQL generated lines exceed 120 characters:\n" + "\n".join(issue.label() for issue in sql)
    assert not list(_generated_package(generated_tree).rglob("_rows.py"))

    bypass = "s" + "kip"
    assert bypass not in Path(__file__).read_text()
    conftest_tree = _parse(Path(__file__).with_name("conftest.py"))
    pgn_fixture = _top_function(conftest_tree, "pgn_bin")
    pytest_calls = [
        node.func.attr
        for node in ast.walk(pgn_fixture)
        if isinstance(node, ast.Call)
        and isinstance(node.func, ast.Attribute)
        and isinstance(node.func.value, ast.Name)
        and node.func.value.id == "pytest"
    ]
    assert pytest_calls.count("fail") == 1
    assert bypass not in pytest_calls
