# @generated by python.gen (pGenie). DO NOT EDIT.
# SPDX-FileCopyrightText: 2026 Viacheslav Shvets
# SPDX-License-Identifier: MIT-0

from __future__ import annotations

from psycopg import AsyncConnection

from .._runtime import execute_rows_affected

SQL = """\
-- rows_affected: UPDATE without RETURNING, keyed by id; exercises the rowcount
-- execution path.
UPDATE specimen
SET rev = rev + 1
WHERE id = %(id)s
"""

_SQL = SQL.encode()


async def bump_specimen_revision(
    conn: AsyncConnection[object],
    *,
    id: int | None,
) -> int:
    params: dict[str, object] = {
        "id": id,
    }
    return await execute_rows_affected(conn, _SQL, params)
