# @generated by python.gen (pGenie). DO NOT EDIT.
# SPDX-FileCopyrightText: 2026 Viacheslav Shvets
# SPDX-License-Identifier: MIT-0

from __future__ import annotations

from collections.abc import Mapping
from dataclasses import dataclass
from typing import cast as _cast

from psycopg import AsyncConnection, Connection

from .._runtime import fetch_optional as _fetch_optional
from ..sync._runtime import fetch_optional as _fetch_optional_sync
from ..types.tag_value import TagValue


@dataclass(frozen=True, slots=True)
class GetTaggedItemRow:
    id: int
    name: str
    tag: TagValue


def _decode_row(row: Mapping[str, object]) -> GetTaggedItemRow:
    return GetTaggedItemRow(
        id=_cast(int, row["id"]),
        name=_cast(str, row["name"]),
        tag=TagValue.pg_decode(row["tag"]),
    )


SQL = """\
-- zero_or_one: select by pk with limit 1; the single-field composite here is
-- purely a result column (no parameter use).
SELECT
  id, name, tag
FROM tagged_item
WHERE id = %(id)s
LIMIT 1
"""

_SQL = SQL.encode()


async def get_tagged_item(
    conn: AsyncConnection[object],
    *,
    id: int | None,
) -> GetTaggedItemRow | None:
    params: dict[str, object] = {
        "id": id,
    }
    return await _fetch_optional(conn, _SQL, params, _decode_row)


def get_tagged_item_sync(
    conn: Connection[object],
    *,
    id: int | None,
) -> GetTaggedItemRow | None:
    params: dict[str, object] = {
        "id": id,
    }
    return _fetch_optional_sync(conn, _SQL, params, _decode_row)
