# @generated by python.gen (pGenie). DO NOT EDIT.
# SPDX-FileCopyrightText: 2026 Viacheslav Shvets
# SPDX-License-Identifier: MIT-0

from __future__ import annotations

from dataclasses import dataclass

from psycopg import AsyncConnection, Connection
from psycopg.rows import args_row as _args_row

from .._runtime import fetch_optional as _fetch_optional
from ..sync._runtime import fetch_optional as _fetch_optional_sync
from .. import types as _db_types

SQL = """\
-- zero_or_one: select by pk with limit 1; the single-field composite here is
-- purely a result column (no parameter use).
SELECT
  id, name, tag
FROM tagged_item
WHERE id = %(id)s
LIMIT 1
"""


@dataclass(frozen=True, slots=True)
class GetTaggedItemRow:
    id: int
    name: str
    tag: _db_types.TagValue


async def get_tagged_item(
    conn: AsyncConnection[object],
    *,
    id: int | None,
) -> GetTaggedItemRow | None:
    params: dict[str, object] = {
        "id": id,
    }
    return await _fetch_optional(conn, SQL, params, _args_row(GetTaggedItemRow))


def get_tagged_item_sync(
    conn: Connection[object],
    *,
    id: int | None,
) -> GetTaggedItemRow | None:
    params: dict[str, object] = {
        "id": id,
    }
    return _fetch_optional_sync(conn, SQL, params, _args_row(GetTaggedItemRow))
