# @generated by python.gen (pGenie); regeneration overwrites manual changes.
# SPDX-FileCopyrightText: 2026 Viacheslav Shvets
# SPDX-License-Identifier: MIT-0

from __future__ import annotations

from dataclasses import dataclass
from datetime import date, datetime
from decimal import Decimal
from uuid import UUID

from psycopg import AsyncConnection, Connection
from psycopg.rows import args_row as _args_row

from .. import types as _db_types
from .._core import JsonValue
from .._runtime import fetch_optional as _fetch_optional
from ..sync._runtime import fetch_optional as _fetch_optional_sync

SQL = """\
-- zero_or_one: select by pk with limit 1.
SELECT
  id, pub_id,
  flag, small, medium, large, ratio, precise,
  title, code, letter, born_on, created_at, amount, blob,
  doc_json, doc_jsonb,
  maybe_text, maybe_int, maybe_uuid, maybe_ts, maybe_num,
  tags, related_ids, grid,
  feeling, origin, codec_payload, codec_payloads, codec_wrapper,
  label, rev, meta
FROM specimen
WHERE id = %(id)s
LIMIT 1
"""


@dataclass(frozen=True, slots=True)
class GetSpecimenRow:
    id: int
    pub_id: UUID
    flag: bool
    small: int
    medium: int
    large: int
    ratio: float
    precise: float
    title: str
    code: str
    letter: str
    born_on: date
    created_at: datetime
    amount: Decimal
    blob: bytes
    doc_json: JsonValue
    doc_jsonb: JsonValue
    maybe_text: str | None
    maybe_int: int | None
    maybe_uuid: UUID | None
    maybe_ts: datetime | None
    maybe_num: Decimal | None
    tags: list[str | None]
    related_ids: list[UUID | None] | None
    grid: list[int | None] | None
    feeling: _db_types.Mood
    origin: _db_types.Point2D | None
    codec_payload: _db_types.ZCodecPayload
    codec_payloads: list[_db_types.ZCodecPayload | None]
    codec_wrapper: _db_types.ACodecWrapper | None
    label: str
    rev: int
    meta: JsonValue


async def get_specimen(
    conn: AsyncConnection[object],
    *,
    id: int | None,
) -> GetSpecimenRow | None:
    params: dict[str, object] = {
        "id": id,
    }
    return await _fetch_optional(conn, SQL, params, _args_row(GetSpecimenRow))


def get_specimen_sync(
    conn: Connection[object],
    *,
    id: int | None,
) -> GetSpecimenRow | None:
    params: dict[str, object] = {
        "id": id,
    }
    return _fetch_optional_sync(conn, SQL, params, _args_row(GetSpecimenRow))
