# @generated by python.gen (pGenie). DO NOT EDIT.
# SPDX-FileCopyrightText: 2026 Viacheslav Shvets
# SPDX-License-Identifier: MIT-0

from __future__ import annotations

from collections.abc import Mapping
from dataclasses import dataclass
from datetime import date, datetime
from decimal import Decimal
from typing import cast as _cast
from uuid import UUID

from psycopg import AsyncConnection, Connection
from psycopg.types.json import Json
from psycopg.types.json import Jsonb

from .._core import JsonValue
from .._runtime import fetch_single as _fetch_single
from ..sync._runtime import fetch_single as _fetch_single_sync
from ..types.a_codec_wrapper import ACodecWrapper
from ..types.mood import Mood
from ..types.point_2_d import Point2D
from ..types.z_codec_payload import ZCodecPayload


@dataclass(frozen=True, slots=True)
class InsertSpecimenRow:
    id: int
    pub_id: UUID
    flag: bool
    small: int
    medium: int
    large: int
    ratio: float
    precise: float
    title: str
    code: str
    letter: str
    born_on: date
    created_at: datetime
    amount: Decimal
    blob: bytes
    doc_json: JsonValue
    doc_jsonb: JsonValue
    maybe_text: str | None
    maybe_int: int | None
    maybe_uuid: UUID | None
    maybe_ts: datetime | None
    maybe_num: Decimal | None
    tags: list[str | None]
    related_ids: list[UUID | None] | None
    grid: list[int | None] | None
    feeling: Mood
    moods: list[Mood | None] | None
    origin: Point2D | None
    codec_payload: ZCodecPayload
    codec_payloads: list[ZCodecPayload | None]
    codec_wrapper: ACodecWrapper | None
    label: str
    rev: int
    meta: JsonValue


def _decode_row(row: Mapping[str, object]) -> InsertSpecimenRow:
    return InsertSpecimenRow(
        id=_cast(int, row["id"]),
        pub_id=_cast(UUID, row["pub_id"]),
        flag=_cast(bool, row["flag"]),
        small=_cast(int, row["small"]),
        medium=_cast(int, row["medium"]),
        large=_cast(int, row["large"]),
        ratio=_cast(float, row["ratio"]),
        precise=_cast(float, row["precise"]),
        title=_cast(str, row["title"]),
        code=_cast(str, row["code"]),
        letter=_cast(str, row["letter"]),
        born_on=_cast(date, row["born_on"]),
        created_at=_cast(datetime, row["created_at"]),
        amount=_cast(Decimal, row["amount"]),
        blob=_cast(bytes, row["blob"]),
        doc_json=_cast(JsonValue, row["doc_json"]),
        doc_jsonb=_cast(JsonValue, row["doc_jsonb"]),
        maybe_text=_cast(str | None, row["maybe_text"]),
        maybe_int=_cast(int | None, row["maybe_int"]),
        maybe_uuid=_cast(UUID | None, row["maybe_uuid"]),
        maybe_ts=_cast(datetime | None, row["maybe_ts"]),
        maybe_num=_cast(Decimal | None, row["maybe_num"]),
        tags=_cast(list[str | None], row["tags"]),
        related_ids=_cast(list[UUID | None] | None, row["related_ids"]),
        grid=_cast(list[int | None] | None, row["grid"]),
        feeling=_cast(Mood, row["feeling"]),
        moods=_cast(list[Mood | None] | None, row["moods"]),
        origin=_cast(Point2D | None, row["origin"]),
        codec_payload=_cast(ZCodecPayload, row["codec_payload"]),
        codec_payloads=_cast(list[ZCodecPayload | None], row["codec_payloads"]),
        codec_wrapper=_cast(ACodecWrapper | None, row["codec_wrapper"]),
        label=_cast(str, row["label"]),
        rev=_cast(int, row["rev"]),
        meta=_cast(JsonValue, row["meta"]),
    )


SQL = """\
-- single row: insert ... returning the full type surface.
-- jsonb param ($doc_jsonb), enum param ($feeling), composite param ($origin).
-- The domain columns (label, rev, meta) get literal/default values rather than
-- parameters. pgn cannot bind a parameter to a checked domain column: a
-- raw domain param is rejected, and a base-type-cast param fails the domain
-- CHECK against the synthetic probe value. Domain mapping is still exercised
-- through the RETURNING clause and the read queries below.
INSERT INTO specimen (
  flag, small, medium, large, ratio, precise,
  title, code, letter, born_on, amount, blob,
  doc_json, doc_jsonb,
  maybe_text, maybe_int, maybe_uuid, maybe_ts, maybe_num,
  tags, related_ids, grid,
  feeling, moods, origin, codec_payload, codec_payloads, codec_wrapper,
  label, rev, meta
)
VALUES (
  %(flag)s, %(small)s, %(medium)s, %(large)s, %(ratio)s, %(precise)s,
  %(title)s, %(code)s, %(letter)s, %(born_on)s, %(amount)s, %(blob)s,
  %(doc_json)s::json, %(doc_jsonb)s::jsonb,
  %(maybe_text)s, %(maybe_int)s, %(maybe_uuid)s, %(maybe_ts)s, %(maybe_num)s,
  %(tags)s, %(related_ids)s, %(grid)s,
  %(feeling)s, %(moods)s::mood[], %(origin)s, %(codec_payload)s, %(codec_payloads)s, %(codec_wrapper)s,
  'specimen', 1, '{}'::jsonb
)
RETURNING
  id, pub_id,
  flag, small, medium, large, ratio, precise,
  title, code, letter, born_on, created_at, amount, blob,
  doc_json, doc_jsonb,
  maybe_text, maybe_int, maybe_uuid, maybe_ts, maybe_num,
  tags, related_ids, grid,
  feeling, moods, origin, codec_payload, codec_payloads, codec_wrapper,
  label, rev, meta
"""

_SQL = SQL.encode()


async def insert_specimen(
    conn: AsyncConnection[object],
    *,
    flag: bool,
    small: int,
    medium: int,
    large: int,
    ratio: float,
    precise: float,
    title: str,
    code: str,
    letter: str,
    born_on: date,
    amount: Decimal,
    blob: bytes,
    doc_json: JsonValue,
    doc_jsonb: JsonValue,
    maybe_text: str | None,
    maybe_int: int | None,
    maybe_uuid: UUID | None,
    maybe_ts: datetime | None,
    maybe_num: Decimal | None,
    tags: list[str | None],
    related_ids: list[UUID | None] | None,
    grid: list[int | None] | None,
    feeling: Mood,
    moods: list[Mood | None] | None,
    origin: Point2D | None,
    codec_payload: ZCodecPayload,
    codec_payloads: list[ZCodecPayload | None],
    codec_wrapper: ACodecWrapper | None,
) -> InsertSpecimenRow:
    params: dict[str, object] = {
        "flag": flag,
        "small": small,
        "medium": medium,
        "large": large,
        "ratio": ratio,
        "precise": precise,
        "title": title,
        "code": code,
        "letter": letter,
        "born_on": born_on,
        "amount": amount,
        "blob": blob,
        "doc_json": Json(doc_json),
        "doc_jsonb": Jsonb(doc_jsonb),
        "maybe_text": maybe_text,
        "maybe_int": maybe_int,
        "maybe_uuid": maybe_uuid,
        "maybe_ts": maybe_ts,
        "maybe_num": maybe_num,
        "tags": tags,
        "related_ids": related_ids,
        "grid": grid,
        "feeling": feeling,
        "moods": moods,
        "origin": origin,
        "codec_payload": codec_payload,
        "codec_payloads": codec_payloads,
        "codec_wrapper": codec_wrapper,
    }
    return await _fetch_single(conn, _SQL, params, _decode_row)


def insert_specimen_sync(
    conn: Connection[object],
    *,
    flag: bool,
    small: int,
    medium: int,
    large: int,
    ratio: float,
    precise: float,
    title: str,
    code: str,
    letter: str,
    born_on: date,
    amount: Decimal,
    blob: bytes,
    doc_json: JsonValue,
    doc_jsonb: JsonValue,
    maybe_text: str | None,
    maybe_int: int | None,
    maybe_uuid: UUID | None,
    maybe_ts: datetime | None,
    maybe_num: Decimal | None,
    tags: list[str | None],
    related_ids: list[UUID | None] | None,
    grid: list[int | None] | None,
    feeling: Mood,
    moods: list[Mood | None] | None,
    origin: Point2D | None,
    codec_payload: ZCodecPayload,
    codec_payloads: list[ZCodecPayload | None],
    codec_wrapper: ACodecWrapper | None,
) -> InsertSpecimenRow:
    params: dict[str, object] = {
        "flag": flag,
        "small": small,
        "medium": medium,
        "large": large,
        "ratio": ratio,
        "precise": precise,
        "title": title,
        "code": code,
        "letter": letter,
        "born_on": born_on,
        "amount": amount,
        "blob": blob,
        "doc_json": Json(doc_json),
        "doc_jsonb": Jsonb(doc_jsonb),
        "maybe_text": maybe_text,
        "maybe_int": maybe_int,
        "maybe_uuid": maybe_uuid,
        "maybe_ts": maybe_ts,
        "maybe_num": maybe_num,
        "tags": tags,
        "related_ids": related_ids,
        "grid": grid,
        "feeling": feeling,
        "moods": moods,
        "origin": origin,
        "codec_payload": codec_payload,
        "codec_payloads": codec_payloads,
        "codec_wrapper": codec_wrapper,
    }
    return _fetch_single_sync(conn, _SQL, params, _decode_row)
