# @generated by python.gen (pGenie). DO NOT EDIT.
# SPDX-FileCopyrightText: 2026 Viacheslav Shvets
# SPDX-License-Identifier: MIT-0

from __future__ import annotations

from datetime import date, datetime
from decimal import Decimal
from uuid import UUID

from psycopg import AsyncConnection
from psycopg.types.json import Json
from psycopg.types.json import Jsonb

from .._core import JsonValue
from .._rows import InsertSpecimenRow, decode_insert_specimen
from .._runtime import fetch_single
from ..types.mood import Mood
from ..types.point_2_d import Point2D

SQL = """\
-- single row: insert ... returning the full type surface.
-- jsonb param ($doc_jsonb), enum param ($feeling), composite param ($origin).
-- The domain columns (label, rev, meta) get literal/default values rather than
-- parameters. pgn cannot bind a parameter to a checked domain column: a
-- raw domain param is rejected, and a base-type-cast param fails the domain
-- CHECK against the synthetic probe value. Domain mapping is still exercised
-- through the RETURNING clause and the read queries below.
INSERT INTO specimen (
  flag, small, medium, large, ratio, precise,
  title, code, letter, born_on, amount, blob,
  doc_json, doc_jsonb,
  maybe_text, maybe_int, maybe_uuid, maybe_ts, maybe_num,
  tags, related_ids, grid,
  feeling, moods, origin,
  label, rev, meta
)
VALUES (
  %(flag)s, %(small)s, %(medium)s, %(large)s, %(ratio)s, %(precise)s,
  %(title)s, %(code)s, %(letter)s, %(born_on)s, %(amount)s, %(blob)s,
  %(doc_json)s::json, %(doc_jsonb)s::jsonb,
  %(maybe_text)s, %(maybe_int)s, %(maybe_uuid)s, %(maybe_ts)s, %(maybe_num)s,
  %(tags)s, %(related_ids)s, %(grid)s,
  %(feeling)s, %(moods)s::mood[], %(origin)s,
  'specimen', 1, '{}'::jsonb
)
RETURNING
  id, pub_id,
  flag, small, medium, large, ratio, precise,
  title, code, letter, born_on, created_at, amount, blob,
  doc_json, doc_jsonb,
  maybe_text, maybe_int, maybe_uuid, maybe_ts, maybe_num,
  tags, related_ids, grid,
  feeling, moods, origin,
  label, rev, meta
"""

_SQL = SQL.encode()


async def insert_specimen(
    conn: AsyncConnection[object],
    *,
    flag: bool,
    small: int,
    medium: int,
    large: int,
    ratio: float,
    precise: float,
    title: str,
    code: str,
    letter: str,
    born_on: date,
    amount: Decimal,
    blob: bytes,
    doc_json: JsonValue,
    doc_jsonb: JsonValue,
    maybe_text: str | None,
    maybe_int: int | None,
    maybe_uuid: UUID | None,
    maybe_ts: datetime | None,
    maybe_num: Decimal | None,
    tags: list[str | None],
    related_ids: list[UUID | None] | None,
    grid: list[int | None] | None,
    feeling: Mood,
    moods: list[Mood | None] | None,
    origin: Point2D | None,
) -> InsertSpecimenRow:
    params: dict[str, object] = {
        "flag": flag,
        "small": small,
        "medium": medium,
        "large": large,
        "ratio": ratio,
        "precise": precise,
        "title": title,
        "code": code,
        "letter": letter,
        "born_on": born_on,
        "amount": amount,
        "blob": blob,
        "doc_json": Json(doc_json),
        "doc_jsonb": Jsonb(doc_jsonb),
        "maybe_text": maybe_text,
        "maybe_int": maybe_int,
        "maybe_uuid": maybe_uuid,
        "maybe_ts": maybe_ts,
        "maybe_num": maybe_num,
        "tags": tags,
        "related_ids": related_ids,
        "grid": grid,
        "feeling": feeling,
        "moods": moods,
        "origin": None if origin is None else (origin.x, origin.y),
    }
    return await fetch_single(conn, _SQL, params, decode_insert_specimen)
