# @generated by python.gen (pGenie); regeneration overwrites manual changes.
# SPDX-FileCopyrightText: 2026 Viacheslav Shvets
# SPDX-License-Identifier: MIT-0

from __future__ import annotations

from dataclasses import dataclass

from psycopg import AsyncConnection, Connection
from psycopg.rows import args_row as _args_row

from .. import types as _db_types
from .._runtime import fetch_single as _fetch_single
from ..sync._runtime import fetch_single as _fetch_single_sync

SQL = """\
-- single row: insert exercising a single-field composite as a parameter and
-- (via RETURNING) as a result column, in the same statement.
INSERT INTO tagged_item (name, tag)
VALUES (%(name)s, %(tag)s)
RETURNING id, name, tag
"""


@dataclass(frozen=True, slots=True)
class InsertTaggedItemRow:
    id: int
    name: str
    tag: _db_types.TagValue


async def insert_tagged_item(
    conn: AsyncConnection[object],
    *,
    name: str,
    tag: _db_types.TagValue,
) -> InsertTaggedItemRow:
    params: dict[str, object] = {
        "name": name,
        "tag": tag,
    }
    return await _fetch_single(conn, SQL, params, _args_row(InsertTaggedItemRow))


def insert_tagged_item_sync(
    conn: Connection[object],
    *,
    name: str,
    tag: _db_types.TagValue,
) -> InsertTaggedItemRow:
    params: dict[str, object] = {
        "name": name,
        "tag": tag,
    }
    return _fetch_single_sync(conn, SQL, params, _args_row(InsertTaggedItemRow))
