# @generated by python.gen (pGenie). DO NOT EDIT.
# SPDX-FileCopyrightText: 2026 Viacheslav Shvets
# SPDX-License-Identifier: MIT-0

from __future__ import annotations

from collections.abc import Mapping
from dataclasses import dataclass
from typing import cast as _cast
from uuid import UUID

from psycopg import AsyncConnection

from .._runtime import fetch_many as _fetch_many
from ..types.mood import Mood


@dataclass(frozen=True, slots=True)
class ListSpecimensByIdsRow:
    id: int
    pub_id: UUID
    feeling: Mood
    title: str


def _decode_row(row: Mapping[str, object]) -> ListSpecimensByIdsRow:
    return ListSpecimensByIdsRow(
        id=_cast(int, row["id"]),
        pub_id=_cast(UUID, row["pub_id"]),
        feeling=Mood.pg_decode(row["feeling"]),
        title=_cast(str, row["title"]),
    )


SQL = """\
-- many: array parameter via = any($pub_ids).
SELECT
  id, pub_id, feeling, title
FROM specimen
WHERE pub_id = ANY(%(pub_ids)s)
ORDER BY id ASC
"""

_SQL = SQL.encode()


async def list_specimens_by_ids(
    conn: AsyncConnection[object],
    *,
    pub_ids: list[UUID | None] | None,
) -> list[ListSpecimensByIdsRow]:
    params: dict[str, object] = {
        "pub_ids": pub_ids,
    }
    return await _fetch_many(conn, _SQL, params, _decode_row)
