# @generated by python.gen (pGenie). DO NOT EDIT.
# SPDX-FileCopyrightText: 2026 Viacheslav Shvets
# SPDX-License-Identifier: MIT-0

from __future__ import annotations

from psycopg import AsyncConnection

from .._rows import ListSpecimensByFeelingRow, decode_list_specimens_by_feeling
from .._runtime import fetch_many
from ..types.mood import Mood

SQL = """\
-- many: select with order by. Enum parameter ($feeling).
SELECT
  id, pub_id, feeling, title, label, rev, origin, tags, meta
FROM specimen
WHERE feeling = %(feeling)s
ORDER BY id ASC
"""

_SQL = SQL.encode()


async def list_specimens_by_feeling(
    conn: AsyncConnection[object],
    *,
    feeling: Mood | None,
) -> list[ListSpecimensByFeelingRow]:
    params: dict[str, object] = {
        "feeling": None if feeling is None else feeling._encode(),
    }
    return await fetch_many(conn, _SQL, params, decode_list_specimens_by_feeling)
