# @generated by python.gen (pGenie). DO NOT EDIT.
# SPDX-FileCopyrightText: 2026 Viacheslav Shvets
# SPDX-License-Identifier: MIT-0

from __future__ import annotations

from collections.abc import Mapping
from dataclasses import dataclass
from typing import cast as _cast
from uuid import UUID

from psycopg import AsyncConnection

from .._core import require_array as _require_array
from .._runtime import fetch_many as _fetch_many
from ..types.mood import Mood


@dataclass(frozen=True, slots=True)
class ListSpecimensByMoodsRow:
    id: int
    pub_id: UUID
    feeling: Mood
    moods: list[Mood | None] | None
    title: str


def _decode_row(row: Mapping[str, object]) -> ListSpecimensByMoodsRow:
    return ListSpecimensByMoodsRow(
        id=_cast(int, row["id"]),
        pub_id=_cast(UUID, row["pub_id"]),
        feeling=Mood.pg_decode(row["feeling"]),
        moods=None if row["moods"] is None else [None if v is None else Mood.pg_decode(v) for v in _cast(list[str | None], _require_array(row["moods"]))],
        title=_cast(str, row["title"]),
    )


SQL = """\
-- many: enum array parameter via = any($moods::mood[]); returns the enum array column.
SELECT
  id, pub_id, feeling, moods, title
FROM specimen
WHERE feeling = ANY(%(moods)s::mood[])
ORDER BY id ASC
"""

_SQL = SQL.encode()


async def list_specimens_by_moods(
    conn: AsyncConnection[object],
    *,
    moods: list[Mood | None] | None,
) -> list[ListSpecimensByMoodsRow]:
    params: dict[str, object] = {
        "moods": None if moods is None else [None if x is None else x.pg_encode() for x in moods],
    }
    return await _fetch_many(conn, _SQL, params, _decode_row)
