# @generated by python.gen (pGenie); regeneration overwrites manual changes.
# SPDX-FileCopyrightText: 2026 Viacheslav Shvets
# SPDX-License-Identifier: MIT-0

from __future__ import annotations

from dataclasses import dataclass

from psycopg import AsyncConnection, Connection
from psycopg.rows import args_row as _args_row

from .._runtime import fetch_many as _fetch_many
from ..sync._runtime import fetch_many as _fetch_many_sync

SQL = """\
-- Keyword-param coverage: the placeholder `class` is a Python reserved word, so
-- the generated signature must use `class_` while the params-dict key and the
-- %%(class)s placeholder keep the raw name. Without sanitization this query emits
-- an un-importable signature, so its presence locks the keyword guard.
SELECT
  id,
  title
FROM specimen
WHERE title = %(class)s
ORDER BY id ASC
"""


@dataclass(frozen=True, slots=True)
class ListSpecimensByClassRow:
    id: int
    title: str


async def list_specimens_by_class(
    conn: AsyncConnection[object],
    *,
    class_: str | None,
) -> list[ListSpecimensByClassRow]:
    params: dict[str, object] = {
        "class": class_,
    }
    return await _fetch_many(conn, SQL, params, _args_row(ListSpecimensByClassRow))


def list_specimens_by_class_sync(
    conn: Connection[object],
    *,
    class_: str | None,
) -> list[ListSpecimensByClassRow]:
    params: dict[str, object] = {
        "class": class_,
    }
    return _fetch_many_sync(conn, SQL, params, _args_row(ListSpecimensByClassRow))
