# @generated by python.gen (pGenie). DO NOT EDIT.
# SPDX-FileCopyrightText: 2026 Viacheslav Shvets
# SPDX-License-Identifier: MIT-0

from __future__ import annotations

from psycopg import AsyncConnection

from .._rows import ListSpecimensByMoodsRow, decode_list_specimens_by_moods
from .._runtime import fetch_many
from ..types.mood import Mood

SQL = """\
-- many: enum array parameter via = any(%(moods)s::mood[]); returns the enum array column.
SELECT
  id, pub_id, feeling, moods, title
FROM specimen
WHERE feeling = ANY(%(moods)s::mood[])
ORDER BY id ASC
"""

_SQL = SQL.encode()


async def list_specimens_by_moods(
    conn: AsyncConnection[object],
    *,
    moods: list[Mood | None] | None,
) -> list[ListSpecimensByMoodsRow]:
    params: dict[str, object] = {
        "moods": moods,
    }
    return await fetch_many(conn, _SQL, params, decode_list_specimens_by_moods)
