# @generated by python.gen (pGenie); regeneration overwrites manual changes.
# SPDX-FileCopyrightText: 2026 Viacheslav Shvets
# SPDX-License-Identifier: MIT-0

from __future__ import annotations

from dataclasses import dataclass

from psycopg import AsyncConnection, Connection
from psycopg.rows import args_row as _args_row

from .._runtime import fetch_many as _fetch_many
from ..sync._runtime import fetch_many as _fetch_many_sync

SQL = """\
-- Keyword result-column coverage: the SQL column aliased to reserved word class
-- stays named \"class\", while the statement-local Row field is class_.
-- psycopg args_row constructs that Row positionally, so no name remapping
-- can hide a missed sanitizer. Without sanitization the canonical statement
-- is invalid Python; this query locks the result-column guard.
SELECT
  id,
  title AS \"class\"
FROM specimen
ORDER BY id ASC
"""


@dataclass(frozen=True, slots=True)
class ListSpecimensKeywordColumnRow:
    id: int
    class_: str


async def list_specimens_keyword_column(
    conn: AsyncConnection[object],
) -> list[ListSpecimensKeywordColumnRow]:
    params: dict[str, object] = {}
    return await _fetch_many(conn, SQL, params, _args_row(ListSpecimensKeywordColumnRow))


def list_specimens_keyword_column_sync(
    conn: Connection[object],
) -> list[ListSpecimensKeywordColumnRow]:
    params: dict[str, object] = {}
    return _fetch_many_sync(conn, SQL, params, _args_row(ListSpecimensKeywordColumnRow))
