# @generated by python.gen (pGenie). DO NOT EDIT.
# SPDX-FileCopyrightText: 2026 Viacheslav Shvets
# SPDX-License-Identifier: MIT-0

from __future__ import annotations

from collections.abc import Mapping
from dataclasses import dataclass
from typing import cast as _cast

from psycopg import AsyncConnection

from .._runtime import fetch_many as _fetch_many


@dataclass(frozen=True, slots=True)
class ListSpecimensByClassRow:
    id: int
    title: str


def _decode_row(row: Mapping[str, object]) -> ListSpecimensByClassRow:
    return ListSpecimensByClassRow(
        id=_cast(int, row["id"]),
        title=_cast(str, row["title"]),
    )


SQL = """\
-- Keyword-param coverage: the placeholder `class` is a Python reserved word, so
-- the generated signature must use `class_` while the params-dict key and the
-- %%(class)s placeholder keep the raw name. Without sanitization this query emits
-- an un-importable signature, so its presence locks the keyword guard.
SELECT
  id,
  title
FROM specimen
WHERE title = %(class)s
ORDER BY id ASC
"""

_SQL = SQL.encode()


async def list_specimens_by_class(
    conn: AsyncConnection[object],
    *,
    class_: str | None,
) -> list[ListSpecimensByClassRow]:
    params: dict[str, object] = {
        "class": class_,
    }
    return await _fetch_many(conn, _SQL, params, _decode_row)
