# @generated by python.gen (pGenie). DO NOT EDIT.
# SPDX-FileCopyrightText: 2026 Viacheslav Shvets
# SPDX-License-Identifier: MIT-0

from __future__ import annotations

from dataclasses import dataclass
from uuid import UUID

from psycopg import AsyncConnection, Connection
from psycopg.rows import args_row as _args_row

from .._runtime import fetch_many as _fetch_many
from ..sync._runtime import fetch_many as _fetch_many_sync
from .. import types as _db_types

SQL = """\
-- many: array parameter via = any($pub_ids).
SELECT
  id, pub_id, feeling, title
FROM specimen
WHERE pub_id = ANY(%(pub_ids)s)
ORDER BY id ASC
"""


@dataclass(frozen=True, slots=True)
class ListSpecimensByIdsRow:
    id: int
    pub_id: UUID
    feeling: _db_types.Mood
    title: str


async def list_specimens_by_ids(
    conn: AsyncConnection[object],
    *,
    pub_ids: list[UUID | None] | None,
) -> list[ListSpecimensByIdsRow]:
    params: dict[str, object] = {
        "pub_ids": pub_ids,
    }
    return await _fetch_many(conn, SQL, params, _args_row(ListSpecimensByIdsRow))


def list_specimens_by_ids_sync(
    conn: Connection[object],
    *,
    pub_ids: list[UUID | None] | None,
) -> list[ListSpecimensByIdsRow]:
    params: dict[str, object] = {
        "pub_ids": pub_ids,
    }
    return _fetch_many_sync(conn, SQL, params, _args_row(ListSpecimensByIdsRow))
