# @generated by python.gen (pGenie). DO NOT EDIT.
# SPDX-FileCopyrightText: 2026 Viacheslav Shvets
# SPDX-License-Identifier: MIT-0

from __future__ import annotations

from collections.abc import Mapping
from dataclasses import dataclass
from typing import cast
from uuid import UUID

from psycopg import AsyncConnection

from .._core import JsonValue
from .._runtime import fetch_many
from ..types.mood import Mood
from ..types.mood import Mood
from ..types.point_2_d import Point2D


@dataclass(frozen=True, slots=True)
class ListSpecimensByFeelingRow:
    id: int
    pub_id: UUID
    feeling: Mood
    title: str
    label: str
    rev: int
    origin: Point2D | None
    tags: list[str | None]
    meta: JsonValue


def decode_list_specimens_by_feeling(row: Mapping[str, object]) -> ListSpecimensByFeelingRow:
    return ListSpecimensByFeelingRow(
        id=cast(int, row["id"]),
        pub_id=cast(UUID, row["pub_id"]),
        feeling=Mood.pg_decode(row["feeling"]),
        title=cast(str, row["title"]),
        label=cast(str, row["label"]),
        rev=cast(int, row["rev"]),
        origin=None if row["origin"] is None else Point2D.pg_decode(row["origin"]),
        tags=cast(list[str | None], row["tags"]),
        meta=cast(JsonValue, row["meta"]),
    )


SQL = """\
-- many: select with order by. Enum parameter ($feeling).
SELECT
  id, pub_id, feeling, title, label, rev, origin, tags, meta
FROM specimen
WHERE feeling = %(feeling)s
ORDER BY id ASC
"""

_SQL = SQL.encode()


async def list_specimens_by_feeling(
    conn: AsyncConnection[object],
    *,
    feeling: Mood | None,
) -> list[ListSpecimensByFeelingRow]:
    params: dict[str, object] = {
        "feeling": None if feeling is None else feeling.pg_encode(),
    }
    return await fetch_many(conn, _SQL, params, decode_list_specimens_by_feeling)
