# @generated by python.gen (pGenie). DO NOT EDIT.
# SPDX-FileCopyrightText: 2026 Viacheslav Shvets
# SPDX-License-Identifier: MIT-0

from __future__ import annotations

from dataclasses import dataclass

from psycopg import AsyncConnection, Connection
from psycopg.rows import args_row as _args_row
from psycopg.types.json import Jsonb

from .._core import JsonValue
from .._runtime import fetch_many as _fetch_many
from ..sync._runtime import fetch_many as _fetch_many_sync

SQL = """\
-- many: nullable parameter via coalesce, jsonb containment parameter, and a
-- domain comparison with the param cast to the base type (pgn cannot bind a
-- domain parameter directly).
SELECT
  id, title, label, meta
FROM specimen
WHERE
  title ILIKE COALESCE(%(title_like)s, '%%')
  AND meta @> %(meta_filter)s::jsonb
  AND label = COALESCE(%(label)s::text, label)
ORDER BY id ASC
"""


@dataclass(frozen=True, slots=True)
class SearchSpecimensRow:
    id: int
    title: str
    label: str
    meta: JsonValue


async def search_specimens(
    conn: AsyncConnection[object],
    *,
    title_like: str | None,
    meta_filter: JsonValue | None,
    label: str | None,
) -> list[SearchSpecimensRow]:
    params: dict[str, object] = {
        "title_like": title_like,
        "meta_filter": None if meta_filter is None else Jsonb(meta_filter),
        "label": label,
    }
    return await _fetch_many(conn, SQL, params, _args_row(SearchSpecimensRow))


def search_specimens_sync(
    conn: Connection[object],
    *,
    title_like: str | None,
    meta_filter: JsonValue | None,
    label: str | None,
) -> list[SearchSpecimensRow]:
    params: dict[str, object] = {
        "title_like": title_like,
        "meta_filter": None if meta_filter is None else Jsonb(meta_filter),
        "label": label,
    }
    return _fetch_many_sync(conn, SQL, params, _args_row(SearchSpecimensRow))
