# @generated by python.gen (pGenie); regeneration overwrites manual changes.
# SPDX-FileCopyrightText: 2026 Viacheslav Shvets
# SPDX-License-Identifier: MIT-0

from dataclasses import dataclass

from .mood import Mood
from .z_codec_payload import ZCodecPayload


@dataclass(frozen=True, slots=True)
class ACodecWrapper:
    payload: ZCodecPayload | None
    feeling: Mood | None
    note: str | None
