# @generated by python.gen (pGenie); regeneration overwrites manual changes.
# SPDX-FileCopyrightText: 2026 Viacheslav Shvets
# SPDX-License-Identifier: MIT-0

from enum import StrEnum


class Mood(StrEnum):
    HAPPY = "happy"
    SAD = "sad"
    MEH = "meh"
