# @generated by python.gen (pGenie). DO NOT EDIT.

from dataclasses import dataclass


@dataclass(frozen=True, slots=True)
class TagValue:
    """Decoding/encoding this composite requires register_types(conn) first.

    Without per-connection registration psycopg returns the value as a
    raw string, which the generated _decode cannot splat into the dataclass.
    """

    value: str | None
