# @generated by python.gen (pGenie). DO NOT EDIT.
# SPDX-FileCopyrightText: 2026 Viacheslav Shvets
# SPDX-License-Identifier: MIT-0

from dataclasses import dataclass


@dataclass(frozen=True, slots=True)
class ZCodecPayload:
    class_: int | None
    pg_decode: str | None
    pg_encode: str | None
