# @generated by python.gen (pGenie). DO NOT EDIT.
# SPDX-FileCopyrightText: 2026 Viacheslav Shvets
# SPDX-License-Identifier: MIT-0

from __future__ import annotations

from psycopg import Connection

from ..._rows import InsertTaggedItemRow, decode_insert_tagged_item
from .._runtime import fetch_single
from ...types.tag_value import TagValue

SQL = """\
-- single row: insert exercising a single-field composite as a parameter and
-- (via RETURNING) as a result column, in the same statement.
INSERT INTO tagged_item (name, tag)
VALUES (%(name)s, %(tag)s)
RETURNING id, name, tag
"""

_SQL = SQL.encode()


def insert_tagged_item(
    conn: Connection[object],
    *,
    name: str,
    tag: TagValue,
) -> InsertTaggedItemRow:
    params: dict[str, object] = {
        "name": name,
        "tag": (tag.value,),
    }
    return fetch_single(conn, _SQL, params, decode_insert_tagged_item)
