# @generated by python.gen (pGenie). DO NOT EDIT.
# SPDX-FileCopyrightText: 2026 Viacheslav Shvets
# SPDX-License-Identifier: MIT-0

from __future__ import annotations

from psycopg import Connection

from ..._rows import ListSpecimensByFeelingRow, decode_list_specimens_by_feeling
from .._runtime import fetch_many
from ...types.mood import Mood

SQL = """\
-- many: select with order by. Enum parameter (%(feeling)s).
SELECT
  id, pub_id, feeling, title, label, rev, origin, tags, meta
FROM specimen
WHERE feeling = %(feeling)s
ORDER BY id ASC
"""

_SQL = SQL.encode()


def list_specimens_by_feeling(
    conn: Connection[object],
    *,
    feeling: Mood | None,
) -> list[ListSpecimensByFeelingRow]:
    params: dict[str, object] = {
        "feeling": feeling,
    }
    return fetch_many(conn, _SQL, params, decode_list_specimens_by_feeling)
