# @generated by python.gen (pGenie). DO NOT EDIT.

from __future__ import annotations

from psycopg import Connection

from ..._rows import ListSpecimensKeywordColumnRow, decode_list_specimens_keyword_column
from .._runtime import fetch_many

SQL = """\
-- Keyword result-column coverage: the column aliased to the reserved word class
-- must emit a dataclass field and decode kwarg of class_ while the row lookup
-- keeps the raw \"class\". Without sanitization the generated _rows.py has a
-- SyntaxError, so this query locks the result-column guard (mirrors
-- list_specimens_by_class for params).
SELECT
  id,
  title AS \"class\"
FROM specimen
ORDER BY id ASC
"""

_SQL = SQL.encode()


def list_specimens_keyword_column(
    conn: Connection[object],
) -> list[ListSpecimensKeywordColumnRow]:
    params: dict[str, object] = {}
    return fetch_many(conn, _SQL, params, decode_list_specimens_keyword_column)
