# @generated by python.gen (pGenie). DO NOT EDIT.

from __future__ import annotations

from uuid import UUID

from psycopg import Connection

from ..._rows import ListSpecimensByIdsRow, decode_list_specimens_by_ids
from .._runtime import fetch_many

SQL = """\
-- many: array parameter via = any(%(pub_ids)s).
SELECT
  id, pub_id, feeling, title
FROM specimen
WHERE pub_id = ANY(%(pub_ids)s)
ORDER BY id ASC
"""

_SQL = SQL.encode()


def list_specimens_by_ids(
    conn: Connection[object],
    *,
    pub_ids: list[UUID | None] | None,
) -> list[ListSpecimensByIdsRow]:
    params: dict[str, object] = {
        "pub_ids": pub_ids,
    }
    return fetch_many(conn, _SQL, params, decode_list_specimens_by_ids)
