# @generated by python.gen (pGenie). DO NOT EDIT.
# SPDX-FileCopyrightText: 2026 Viacheslav Shvets
# SPDX-License-Identifier: MIT-0

from __future__ import annotations

from psycopg import Connection
from psycopg.types.json import Jsonb

from ..._rows import SearchSpecimensRow, decode_search_specimens
from .._runtime import JsonValue, fetch_many

SQL = """\
-- many: nullable parameter via coalesce, jsonb containment parameter, and a
-- domain comparison with the param cast to the base type (pgn cannot bind a
-- domain parameter directly).
SELECT
  id, title, label, meta
FROM specimen
WHERE
  title ILIKE COALESCE(%(title_like)s, '%%')
  AND meta @> %(meta_filter)s::jsonb
  AND label = COALESCE(%(label)s::text, label)
ORDER BY id ASC
"""

_SQL = SQL.encode()


def search_specimens(
    conn: Connection[object],
    *,
    title_like: str | None,
    meta_filter: JsonValue | None,
    label: str | None,
) -> list[SearchSpecimensRow]:
    params: dict[str, object] = {
        "title_like": title_like,
        "meta_filter": None if meta_filter is None else Jsonb(meta_filter),
        "label": label,
    }
    return fetch_many(conn, _SQL, params, decode_search_specimens)
