let Lude = ../Deps/Lude.dhall

let Prelude = ../Deps/Prelude.dhall

let Model = ../Deps/Contract.dhall

let Sdk = ../Deps/Sdk.dhall

let QueryGen = ./Query.dhall

let CustomTypeGen = ./CustomType.dhall

let CoreModule = ../Templates/CoreModule.dhall

let RuntimeModule = ../Templates/RuntimeModule.dhall

let InitModule = ../Templates/InitModule.dhall

let TypesInit = ../Templates/TypesInit.dhall

let RegisterModule = ../Templates/RegisterModule.dhall

let FacadeModule = ../Templates/FacadeModule.dhall

let RowsModule = ../Templates/RowsModule.dhall

let ImportSet = ../Structures/ImportSet.dhall

let Surface = ../Structures/Surface.dhall

let OnUnsupported = ../Structures/OnUnsupported.dhall

let Report = { path : List Text, message : Text }

-- The generator's public Config: every field is independently Optional, so a
-- project may omit the whole `config:` block or any subset of its keys.
-- `run` below resolves the fallbacks itself (packageName from the project
-- name, emitSync off, onUnsupported Fail); there is no separate config type
-- or resolve step between package.dhall and here.
let Config =
      { packageName : Optional Text
      , emitSync : Optional Bool
      , onUnsupported : Optional OnUnsupported.Mode
      }

-- The fully-resolved shape every downstream interpreter (Query, CustomType,
-- and everything below them) actually declares as its own `Config`.
let ResolvedConfig =
      { packageName : Text
      , importName : Text
      , emitSync : Bool
      , onUnsupported : OnUnsupported.Mode
      }

let Input = Model.Project

let Output = Lude.Files.Type

-- Header of every emitted .py file. The @generated + DO NOT EDIT convention
-- (Go/Phabricator/linguist) marks the file as machine-written; tooling and
-- reviewers key on it. The SPDX pair (REUSE convention) licenses the emitted
-- file itself as MIT-0: the template text it reproduces is the generator
-- author's copyright, granted here attribution-free so the containing
-- project can use it under its own terms and compliance scanners see a
-- standard permissive id instead of the generator's license.
-- Prepended once here so it applies to all modules.
let generatedHeader =
      ''
      # @generated by python.gen (pGenie). DO NOT EDIT.
      # SPDX-FileCopyrightText: 2026 Viacheslav Shvets
      # SPDX-License-Identifier: MIT-0

      ''

let withHeader =
      \(file : Lude.File.Type) ->
        { path = file.path, content = generatedHeader ++ file.content }

-- Schema-qualified type names for psycopg CompositeInfo.fetch (search-path
-- safe). Reads CustomTypeGen.Output (already a combineOutputs parameter, and
-- already the post-Skip-filter surviving set), not Model.CustomType, so
-- there is no second List Model.CustomType parameter to thread through.
let compositePgNames =
      \(customTypes : List CustomTypeGen.Output) ->
        Prelude.List.map
          CustomTypeGen.Output
          Text
          (\(ct : CustomTypeGen.Output) -> "${ct.pgSchema}.${ct.pgName}")
          ( Prelude.List.filter
              CustomTypeGen.Output
              (\(ct : CustomTypeGen.Output) -> merge { Composite = True, Enum = False } ct.kind)
              customTypes
          )

-- Enum TypeInfos are registered too so enum arrays parse (see RegisterModule).
let enumPgNames =
      \(customTypes : List CustomTypeGen.Output) ->
        Prelude.List.map
          CustomTypeGen.Output
          Text
          (\(ct : CustomTypeGen.Output) -> "${ct.pgSchema}.${ct.pgName}")
          ( Prelude.List.filter
              CustomTypeGen.Output
              (\(ct : CustomTypeGen.Output) -> merge { Composite = False, Enum = True } ct.kind)
              customTypes
          )

let combineOutputs =
      \(config : ResolvedConfig) ->
      \(input : Input) ->
      -- Already the post-Skip-filter surviving set (see `run`); equal to
      -- input.queries' compiled outputs verbatim when nothing was skipped
      -- (including every Fail-mode run, since Fail never drops anything).
      -- Facade/statement/row entries are built from this, not input.queries,
      -- so a skipped query leaves no dangling export.
      \(queries : List QueryGen.Output) ->
      -- Same as above, but for customTypes. Facade/typesInit/register
      -- entries are built from this, not input.customTypes, so a skipped
      -- type leaves no dangling export.
      \(customTypes : List CustomTypeGen.Output) ->
        -- The generator emits the _generated subtree plus the package-root
        -- __init__.py facade. The rest of the shell (pyproject.toml, py.typed) is
        -- hand-written and committed once, never overwritten by generation.
        let packagePrefix = "src/${config.importName}/"

        let srcPrefix = packagePrefix ++ "_generated/"

        let topInit =
              { path = srcPrefix ++ "__init__.py"
              , content =
                  InitModule.run
                    { docstring =
                        "Generated database client for ${config.packageName}."
                    }
              }

        let facadeStatements =
              Prelude.List.map
                QueryGen.Output
                FacadeModule.StatementExport
                ( \(query : QueryGen.Output) ->
                    { functionName = query.functionName
                    , rowClassName = query.rowClassName
                    }
                )
                queries

        let facadeTypes =
              Prelude.List.map
                CustomTypeGen.Output
                FacadeModule.TypeExport
                ( \(ct : CustomTypeGen.Output) ->
                    { moduleName = ct.moduleName, className = ct.typeName }
                )
                customTypes

        let asyncFacade =
              { path = packagePrefix ++ "__init__.py"
              , content =
                  FacadeModule.run
                    { generatedPrefix = "._generated"
                    , statementsPath = "statements"
                    , statements = facadeStatements
                    , types = facadeTypes
                    }
              }

        -- Surface-agnostic; performs no I/O, so exactly one copy is emitted
        -- regardless of surface. Both _runtime.py modules re-export from it.
        let coreModule =
              { path = srcPrefix ++ "_core.py", content = CoreModule.run {=} }

        let runtimeModule =
              { path = srcPrefix ++ "_runtime.py", content = RuntimeModule.run {=} }

        let statementsInit =
              { path = srcPrefix ++ "statements/__init__.py"
              , content =
                  InitModule.run { docstring = "Generated SQL statements." }
              }

        -- The shared Row dataclasses + decode functions, imported by both the
        -- async and sync statement modules so the two surfaces share one set of
        -- types (cross-surface identity).
        let rowDefs =
              Prelude.List.concatMap
                QueryGen.Output
                RowsModule.RowDef
                ( \(query : QueryGen.Output) ->
                    Prelude.Optional.toList RowsModule.RowDef query.rowDef
                )
                queries

        let rowImports =
              ImportSet.combineAll
                ( Prelude.List.map
                    QueryGen.Output
                    ImportSet.Type
                    (\(query : QueryGen.Output) -> query.rowImports)
                    queries
                )

        let rowsFiles =
              if    Prelude.List.null RowsModule.RowDef rowDefs
              then  [] : List Lude.File.Type
              else  [ { path = srcPrefix ++ "_rows.py"
                      , content =
                          RowsModule.run { rows = rowDefs, imports = rowImports }
                      }
                    ]

        let asyncStatementFiles =
              Prelude.List.map
                QueryGen.Output
                Lude.File.Type
                ( \(query : QueryGen.Output) ->
                    { path = srcPrefix ++ query.asyncModulePath
                    , content = query.asyncContent
                    }
                )
                queries

        let typeFiles =
              Prelude.List.map
                CustomTypeGen.Output
                Lude.File.Type
                ( \(ct : CustomTypeGen.Output) ->
                    { path = srcPrefix ++ ct.modulePath
                    , content = ct.moduleContent
                    }
                )
                customTypes

        let typesInitExports =
              Prelude.List.map
                CustomTypeGen.Output
                TypesInit.Export
                (\(ct : CustomTypeGen.Output) -> { moduleName = ct.moduleName, typeName = ct.typeName })
                customTypes

        let typesInitFiles =
              if    Prelude.List.null CustomTypeGen.Output customTypes
              then  [] : List Lude.File.Type
              else  [ { path = srcPrefix ++ "types/__init__.py"
                      , content = TypesInit.run { exports = typesInitExports }
                      }
                    ]

        let compositeNames = compositePgNames customTypes

        let enumNames = enumPgNames customTypes

        let hasCustomRegistration =
              Prelude.Bool.not
                ( Prelude.Bool.and
                    [ Prelude.List.null Text compositeNames
                    , Prelude.List.null Text enumNames
                    ]
                )

        let registerFiles =
              if    hasCustomRegistration
              then  [ { path = srcPrefix ++ "_register.py"
                      , content =
                          RegisterModule.run
                            { compositeNames, enumNames, surface = Surface.async }
                      }
                    ]
              else  [] : List Lude.File.Type

        -- The sync surface mirrors the async one under `sync/`, gated on
        -- config.emitSync. It reuses the shared `_rows.py` and `types/`, so only
        -- the I/O wrappers (statements, runtime, register) and the sync facade
        -- are sync-specific.
        let syncStatementFiles =
              Prelude.List.map
                QueryGen.Output
                Lude.File.Type
                ( \(query : QueryGen.Output) ->
                    { path = srcPrefix ++ query.syncModulePath
                    , content = query.syncContent
                    }
                )
                queries

        let syncSubpackageInit =
              { path = srcPrefix ++ "sync/__init__.py"
              , content =
                  InitModule.run { docstring = "Generated sync database client." }
              }

        let syncStatementsInit =
              { path = srcPrefix ++ "sync/statements/__init__.py"
              , content =
                  InitModule.run { docstring = "Generated SQL statements (sync)." }
              }

        let syncRuntime =
              { path = srcPrefix ++ "sync/_runtime.py"
              , content = RuntimeModule.runSync {=}
              }

        let syncRegisterFiles =
              if    hasCustomRegistration
              then  [ { path = srcPrefix ++ "sync/_register.py"
                      , content =
                          RegisterModule.run
                            { compositeNames, enumNames, surface = Surface.sync }
                      }
                    ]
              else  [] : List Lude.File.Type

        let syncFacade =
              { path = packagePrefix ++ "sync/__init__.py"
              , content =
                  FacadeModule.run
                    { generatedPrefix = ".._generated"
                    , statementsPath = "sync.statements"
                    , statements = facadeStatements
                    , types = facadeTypes
                    }
              }

        let syncFiles =
              if    config.emitSync
              then    [ syncSubpackageInit
                      , syncRuntime
                      , syncStatementsInit
                      , syncFacade
                      ]
                    # syncRegisterFiles
                    # syncStatementFiles
              else  [] : List Lude.File.Type

        let asyncStaticFiles =
              [ asyncFacade, topInit, coreModule, runtimeModule, statementsInit ]

        let allFiles =
                asyncStaticFiles
              # registerFiles
              # rowsFiles
              # typesInitFiles
              # typeFiles
              # asyncStatementFiles
              # syncFiles

        in  Prelude.List.map Lude.File.Type Lude.File.Type withHeader allFiles
          : Output

-- Per-element keep/drop decision plus its warning, computed once from a
-- single QueryGen.run call and reused for both the Skip filter and the
-- warning list. Custom types use a pair of plain functions instead of an
-- equivalent record (see `typeSucceeds`/`typeWarning` below) purely because
-- that was the faster shape empirically for the type side, and the query
-- side re-uses `queryChecks` because calling QueryGen.run config query from
-- more than one place in this function (once to decide keep/drop, again to
-- render, again for a warning -- each a fresh, separate call site in the
-- source) measurably multiplies Dhall's normalization cost per extra call
-- site, confirmed by bisection against `pgn generate` wall time (a few
-- seconds regressed to minutes with three call sites; this file keeps it to
-- two: one to build `queryChecks`, one for the final render).
let QueryCheck = { query : Model.Query, keep : Bool, warning : Optional Report }

let run =
      \(config : Config) ->
      \(input : Input) ->
        -- config's fields are independently Optional (a project may omit the
        -- whole config: block or any subset of its keys); the fallbacks are
        -- resolved here rather than in a separate config type or resolve
        -- step, since this is the root interpreter and Config above is
        -- exactly the generator's public Config.
        let packageName =
              Prelude.Optional.fold
                Text
                config.packageName
                Text
                (\(t : Text) -> t)
                input.name.inKebabCase

        let emitSync =
              Prelude.Optional.fold
                Bool
                config.emitSync
                Bool
                (\(b : Bool) -> b)
                False

        let onUnsupported =
              Prelude.Optional.fold
                OnUnsupported.Mode
                config.onUnsupported
                OnUnsupported.Mode
                (\(m : OnUnsupported.Mode) -> m)
                OnUnsupported.Mode.Fail

        let importName = Prelude.Text.replace "-" "_" packageName

        let resolvedConfig
            : ResolvedConfig
            = { packageName, importName, emitSync, onUnsupported }

        let skip = merge { Fail = False, Skip = True } resolvedConfig.onUnsupported

        let typeSucceeds
            : Model.CustomType -> Bool
            = \(ct : Model.CustomType) ->
                merge
                  { Ok =
                      \(_ : { value : CustomTypeGen.Output, warnings : List Report }) ->
                        True
                  , Err = \(_ : Report) -> False
                  }
                  (CustomTypeGen.run resolvedConfig ct)

        -- Nested under the type's own name so the warning names the type
        -- that failed, not just the inner member/column that triggered it
        -- (CustomType.run itself does not).
        let typeWarning
            : Model.CustomType -> Optional Report
            = \(ct : Model.CustomType) ->
                merge
                  { Ok =
                      \(_ : { value : CustomTypeGen.Output, warnings : List Report }) ->
                        None Report
                  , Err =
                      \(err : Report) -> Some { path = [ ct.name.inSnakeCase ] # err.path, message = err.message }
                  }
                  (CustomTypeGen.run resolvedConfig ct)

        -- A skipped custom type resolves to Absent for any query that
        -- references it, and that query's own Member/ParamsMember
        -- resolution fails with "Custom type not found" -- caught the same
        -- way any other unsupported shape is, cascading the skip onto every
        -- dependent query.
        let effectiveCustomTypes
            : List Model.CustomType
            = if    skip
              then  Prelude.List.filter Model.CustomType typeSucceeds input.customTypes
              else  input.customTypes

        -- Fail mode: identical to the pre-Skip code (traverseList straight
        -- over input.customTypes), so its error message/path is unchanged.
        let typesForCombine
            : Lude.Compiled.Type (List CustomTypeGen.Output)
            = Lude.Compiled.traverseList
                Model.CustomType
                CustomTypeGen.Output
                (\(ct : Model.CustomType) -> CustomTypeGen.run resolvedConfig ct)
                effectiveCustomTypes

        let queryChecks
            : List QueryCheck
            = Prelude.List.map
                Model.Query
                QueryCheck
                ( \(query : Model.Query) ->
                    merge
                      { Ok =
                          \(_ : { value : QueryGen.Output, warnings : List Report }) ->
                            { query, keep = True, warning = None Report }
                      , Err = \(err : Report) -> { query, keep = False, warning = Some err }
                      }
                      (QueryGen.run resolvedConfig query)
                )
                input.queries

        let effectiveQueries
            : List Model.Query
            = if    skip
              then  Prelude.List.map
                      QueryCheck
                      Model.Query
                      (\(qc : QueryCheck) -> qc.query)
                      (Prelude.List.filter QueryCheck (\(qc : QueryCheck) -> qc.keep) queryChecks)
              else  input.queries

        -- Fail mode: identical to the pre-Skip code (traverseList straight
        -- over input.queries), so its error message/path is unchanged.
        let queriesForCombine
            : Lude.Compiled.Type (List QueryGen.Output)
            = Lude.Compiled.traverseList
                Model.Query
                QueryGen.Output
                (\(query : Model.Query) -> QueryGen.run resolvedConfig query)
                effectiveQueries

        let skipWarnings
            : List Report
            = if    skip
              then    Prelude.List.unpackOptionals
                        Report
                        (Prelude.List.map Model.CustomType (Optional Report) typeWarning input.customTypes)
                    # Prelude.List.unpackOptionals
                        Report
                        (Prelude.List.map QueryCheck (Optional Report) (\(qc : QueryCheck) -> qc.warning) queryChecks)
              else  [] : List Report

        let combined
            : Lude.Compiled.Type Output
            = Lude.Compiled.map2
                (List QueryGen.Output)
                (List CustomTypeGen.Output)
                Output
                (combineOutputs resolvedConfig input)
                queriesForCombine
                typesForCombine

        in  Lude.Compiled.appendWarnings Output skipWarnings combined

in  Sdk.Sigs.interpreter Config Input Output run
