let Lude = ../Deps/Lude.dhall

let Prelude = ../Deps/Prelude.dhall

let Model = ../Deps/Contract.dhall

let Sdk = ../Deps/Sdk.dhall

let CustomKind = ../Structures/CustomKind.dhall

let PyIdent = ../Structures/PyIdent.dhall

let Value = ./Value.dhall

let QueryGen = ./Query.dhall

let CustomTypeGen = ./CustomType.dhall

let CoreModule = ../Templates/CoreModule.dhall

let RuntimeModule = ../Templates/RuntimeModule.dhall

let InitModule = ../Templates/InitModule.dhall

let TypesInit = ../Templates/TypesInit.dhall

let RegisterModule = ../Templates/RegisterModule.dhall

let FacadeModule = ../Templates/FacadeModule.dhall

let OnUnsupported = ../Structures/OnUnsupported.dhall

let Report = { path : List Text, message : Text }

-- The generator's public Config: every field is independently Optional, so a
-- project may omit the whole `config:` block or any subset of its keys.
-- `run` below resolves the fallbacks itself (packageName from the project
-- name, sync emission off, onUnsupported Fail); there is no separate config type
-- or resolve step between package.dhall and here.
let Config =
      { packageName : Optional Text
      , emitSync : Optional Bool
      , onUnsupported : Optional OnUnsupported.Mode
      }

-- The fully-resolved shape every downstream interpreter (Query, CustomType,
-- and everything below them) actually declares as its own `Config`.
let ResolvedConfig =
      { packageName : Text
      , importName : Text
      , emitSync : Bool
      , onUnsupported : OnUnsupported.Mode
      }

let Input = Model.Project

let Output = Lude.Files.Type

-- Header of every emitted .py file. The @generated + DO NOT EDIT convention
-- (Go/Phabricator/linguist) marks the file as machine-written; tooling and
-- reviewers key on it. The SPDX pair (REUSE convention) licenses the emitted
-- file itself as MIT-0: the template text it reproduces is the generator
-- author's copyright, granted here attribution-free so the containing
-- project can use it under its own terms and compliance scanners see a
-- standard permissive id instead of the generator's license.
-- Prepended once here so it applies to all modules.
let generatedHeader =
      ''
      # @generated by python.gen (pGenie). DO NOT EDIT.
      # SPDX-FileCopyrightText: 2026 Viacheslav Shvets
      # SPDX-License-Identifier: MIT-0

      ''

let withHeader =
      \(file : Lude.File.Type) ->
        { path = file.path, content = generatedHeader ++ file.content }

let lookupConfig
    : ResolvedConfig
    = { packageName = ""
      , importName = ""
      , emitSync = False
      , onUnsupported = OnUnsupported.Mode.Fail
      }

let memberPyType =
      \(member : Model.Member) ->
        let valuePyType =
              merge
                { Ok =
                    \(wrapped : { value : Value.Output, warnings : List Report }) ->
                      wrapped.value.pyType
                , Err = \(_ : Report) -> "object"
                }
                (Value.run lookupConfig member.value)

        in  valuePyType ++ (if member.isNullable then " | None" else "")

let compositeFields =
      \(members : List Model.Member) ->
        Prelude.List.map
          Model.Member
          CustomKind.CompositeField
          ( \(member : Model.Member) ->
              { fieldName = PyIdent.pySafeName member.name.inSnakeCase
              , pyType = memberPyType member
              }
          )
          members

let IndexedCustomType = { index : Natural, value : Model.CustomType }

let buildLookup =
      \(customTypes : List Model.CustomType) ->
        Prelude.List.fold
          IndexedCustomType
          (Prelude.List.indexed Model.CustomType customTypes)
          CustomKind.Lookup
          ( \(entry : IndexedCustomType) ->
            \(rest : CustomKind.Lookup) ->
            \(name : Model.Name) ->
              let customType = entry.value

              -- Text/equal is a pgn embedded-Dhall builtin. The upstream exit is
              -- a stable custom kind or id on Scalar.Custom.
              in  if    Text/equal
                          name.inSnakeCase
                          customType.name.inSnakeCase
                  then  merge
                          { Composite =
                              \(members : List Model.Member) ->
                                CustomKind.TypeKind.Composite
                                  { fields = compositeFields members
                                  , order = entry.index
                                  }
                          , Enum =
                              \(_ : List Model.EnumVariant) ->
                                CustomKind.TypeKind.Enum entry.index
                          , Domain =
                              \(_ : Model.Value) -> CustomKind.TypeKind.Absent
                          }
                          customType.definition
                  else  rest name
          )
          (\(_ : Model.Name) -> CustomKind.TypeKind.Absent)

let sameOrder =
      \(left : Natural) ->
      \(right : Natural) ->
        Natural/isZero (Natural/subtract left right)
        && Natural/isZero (Natural/subtract right left)

let containsOrder =
      \(order : Natural) ->
      \(customTypes : List CustomTypeGen.Output) ->
        Prelude.List.any
          CustomTypeGen.Output
          (\(custom : CustomTypeGen.Output) -> sameOrder order custom.order)
          customTypes

let dependenciesReady =
      \(emitted : List CustomTypeGen.Output) ->
      \(custom : CustomTypeGen.Output) ->
        Prelude.Bool.not
          ( Prelude.List.any
              Natural
              (\(dependency : Natural) -> Prelude.Bool.not (containsOrder dependency emitted))
              custom.dependencies
          )

let RegistrationState =
      { emitted : List CustomTypeGen.Output
      , remaining : List CustomTypeGen.Output
      }

let registrationOrder =
      \(customTypes : List CustomTypeGen.Output) ->
        let enums =
              Prelude.List.filter
                CustomTypeGen.Output
                ( \(custom : CustomTypeGen.Output) ->
                    merge { Enum = True, Composite = False } custom.kind
                )
                customTypes

        let composites =
              Prelude.List.filter
                CustomTypeGen.Output
                ( \(custom : CustomTypeGen.Output) ->
                    merge { Enum = False, Composite = True } custom.kind
                )
                customTypes

        let pass =
              \(state : RegistrationState) ->
                let ready =
                      Prelude.List.filter
                        CustomTypeGen.Output
                        (dependenciesReady state.emitted)
                        state.remaining

                let blocked =
                      Prelude.List.filter
                        CustomTypeGen.Output
                        ( \(custom : CustomTypeGen.Output) ->
                            Prelude.Bool.not
                              (dependenciesReady state.emitted custom)
                        )
                        state.remaining

                in  { emitted = state.emitted # ready, remaining = blocked }

        let ordered =
              Natural/fold
                (Prelude.List.length CustomTypeGen.Output customTypes)
                RegistrationState
                pass
                { emitted = enums, remaining = composites }

        let unresolved =
              Prelude.Text.concatMapSep
                ", "
                CustomTypeGen.Output
                ( \(custom : CustomTypeGen.Output) ->
                    "${custom.pgSchema}.${custom.pgName}"
                )
                ordered.remaining

        in  if Prelude.List.null CustomTypeGen.Output ordered.remaining
            then  Lude.Compiled.ok (List CustomTypeGen.Output) ordered.emitted
            else  Lude.Compiled.report
                    (List CustomTypeGen.Output)
                    [ "register_types" ]
                    "Unresolved or cyclic custom type dependencies: ${unresolved}"

let combineOutputs =
      \(config : ResolvedConfig) ->
      \(input : Input) ->
      -- Already the post-Skip-filter surviving set (see `run`); equal to
      -- input.queries' compiled outputs verbatim when nothing was skipped
      -- (including every Fail-mode run, since Fail never drops anything).
      -- Facade/statement/row entries are built from this, not input.queries,
      -- so a skipped query leaves no dangling export.
      \(queries : List QueryGen.Output) ->
      -- Same as above, but for customTypes. Facade/typesInit/register
      -- entries are built from this, not input.customTypes, so a skipped
      -- type leaves no dangling export.
      \(customTypes : List CustomTypeGen.Output) ->
      -- Same compiled custom types in dependency-first order, used only by the
      -- shared register module. File and facade order remains project order.
      \(registrationTypes : List CustomTypeGen.Output) ->
        -- The generator emits the _generated subtree plus the package-root
        -- __init__.py facade. The rest of the shell (pyproject.toml, py.typed) is
        -- hand-written and committed once, never overwritten by generation.
        let packagePrefix = "src/${config.importName}/"

        let srcPrefix = packagePrefix ++ "_generated/"

        let topInit =
              { path = srcPrefix ++ "__init__.py"
              , content =
                  InitModule.run
                    { docstring =
                        "Generated database client for ${config.packageName}."
                    }
              }

        let facadeStatements =
              Prelude.List.map
                QueryGen.Output
                FacadeModule.StatementExport
                ( \(query : QueryGen.Output) ->
                    { functionName = query.functionName
                    , rowClassName = query.rowClassName
                    }
                )
                queries

        let facadeTypes =
              Prelude.List.map
                CustomTypeGen.Output
                FacadeModule.TypeExport
                ( \(ct : CustomTypeGen.Output) ->
                    { moduleName = ct.moduleName, className = ct.typeName }
                )
                customTypes

        -- Surface-agnostic; performs no I/O, so exactly one copy is emitted
        -- regardless of surface. Both runtime bodies re-export from it.
        let coreModule =
              { path = srcPrefix ++ "_core.py", content = CoreModule.run {=} }

        let runtimeModule =
              { path = srcPrefix ++ "_runtime.py"
              , content = RuntimeModule.run {=}
              }

        let syncRuntimeFiles =
              if    config.emitSync
              then  [ { path = srcPrefix ++ "sync/_runtime.py"
                      , content = RuntimeModule.runSync {=}
                      }
                    ]
              else  [] : List Lude.File.Type

        let statementsInit =
              { path = srcPrefix ++ "statements/__init__.py"
              , content =
                  InitModule.run { docstring = "Generated SQL statements." }
              }

        let statementFiles =
              Prelude.List.map
                QueryGen.Output
                Lude.File.Type
                ( \(query : QueryGen.Output) ->
                    { path = srcPrefix ++ query.modulePath
                    , content = query.content
                    }
                )
                queries

        let typeFiles =
              Prelude.List.map
                CustomTypeGen.Output
                Lude.File.Type
                ( \(ct : CustomTypeGen.Output) ->
                    { path = srcPrefix ++ ct.modulePath
                    , content = ct.moduleContent
                    }
                )
                customTypes

        let typesInitExports =
              Prelude.List.map
                CustomTypeGen.Output
                TypesInit.Export
                (\(ct : CustomTypeGen.Output) -> { moduleName = ct.moduleName, typeName = ct.typeName })
                customTypes

        let typesInitFiles =
              if    Prelude.List.null CustomTypeGen.Output customTypes
              then  [] : List Lude.File.Type
              else  [ { path = srcPrefix ++ "types/__init__.py"
                      , content = TypesInit.run { exports = typesInitExports }
                      }
                    ]

        let hasCustomRegistration =
              Prelude.Bool.not
                (Prelude.List.null CustomTypeGen.Output registrationTypes)

        let registrationEntries =
              Prelude.List.map
                CustomTypeGen.Output
                RegisterModule.CustomType
                ( \(custom : CustomTypeGen.Output) ->
                    { typeName = custom.typeName
                    , moduleName = custom.moduleName
                    , pgSchema = custom.pgSchema
                    , pgName = custom.pgName
                    , kind = custom.kind
                    }
                )
                registrationTypes

        let registerFiles =
              if    hasCustomRegistration
              then  [ { path = srcPrefix ++ "_register.py"
                      , content =
                          RegisterModule.run
                            { customTypes = registrationEntries
                            , emitSync = config.emitSync
                            }
                      }
                    ]
              else  [] : List Lude.File.Type

        let registrationSource =
              if    hasCustomRegistration
              then  Some "register_types"
              else  None Text

        let facade =
              { path = packagePrefix ++ "__init__.py"
              , content =
                  FacadeModule.run
                    { statements = facadeStatements
                    , types = facadeTypes
                    , generatedPrefix = "._generated"
                    , functionSuffix = ""
                    , registrationSource
                    , includeSyncModule = config.emitSync
                    }
              }

        let syncFacadeFiles =
              if    config.emitSync
              then  [ { path = packagePrefix ++ "sync/__init__.py"
                      , content =
                          FacadeModule.run
                            { statements = facadeStatements
                            , types = facadeTypes
                            , generatedPrefix = ".._generated"
                            , functionSuffix = "_sync"
                            , registrationSource =
                                if    hasCustomRegistration
                                then  Some "register_types_sync"
                                else  None Text
                            , includeSyncModule = False
                            }
                      }
                    ]
              else  [] : List Lude.File.Type

        let staticFiles =
              [ facade, topInit, coreModule, runtimeModule, statementsInit ]
              # syncFacadeFiles
              # syncRuntimeFiles

        let allFiles =
                staticFiles
              # registerFiles
              # typesInitFiles
              # typeFiles
              # statementFiles

        in  Prelude.List.map Lude.File.Type Lude.File.Type withHeader allFiles
          : Output

-- Per-element keep/drop decision plus its warning, computed once from a
-- single QueryGen.run call and reused for both the Skip filter and the
-- warning list. Custom types use a pair of plain functions instead of an
-- equivalent record (see `typeSucceeds`/`typeWarning` below) purely because
-- that was the faster shape empirically for the type side, and the query
-- side re-uses `queryChecks` because calling QueryGen.run config lookup query from
-- more than one place in this function (once to decide keep/drop, again to
-- render, again for a warning -- each a fresh, separate call site in the
-- source) measurably multiplies Dhall's normalization cost per extra call
-- site, confirmed by bisection against `pgn generate` wall time (a few
-- seconds regressed to minutes with three call sites; this file keeps it to
-- two: one to build `queryChecks`, one for the final render).
let QueryCheck = { query : Model.Query, keep : Bool, warning : Optional Report }

let run =
      \(config : Config) ->
      \(input : Input) ->
        -- config's fields are independently Optional (a project may omit the
        -- whole config: block or any subset of its keys); the fallbacks are
        -- resolved here rather than in a separate config type or resolve
        -- step, since this is the root interpreter and Config above is
        -- exactly the generator's public Config.
        let packageName =
              Prelude.Optional.fold
                Text
                config.packageName
                Text
                (\(t : Text) -> t)
                input.name.inKebabCase

        let emitSync =
              Prelude.Optional.fold
                Bool
                config.emitSync
                Bool
                (\(b : Bool) -> b)
                False

        let onUnsupported =
              Prelude.Optional.fold
                OnUnsupported.Mode
                config.onUnsupported
                OnUnsupported.Mode
                (\(m : OnUnsupported.Mode) -> m)
                OnUnsupported.Mode.Fail

        let importName = Prelude.Text.replace "-" "_" packageName

        let resolvedConfig
            : ResolvedConfig
            = { packageName, importName, emitSync, onUnsupported }

        let skip = merge { Fail = False, Skip = True } resolvedConfig.onUnsupported

        let typeSucceedsWith =
              \(candidateLookup : CustomKind.Lookup) ->
              \(ct : Model.CustomType) ->
                merge
                  { Ok =
                      \(_ : { value : CustomTypeGen.Output, warnings : List Report }) ->
                        True
                  , Err = \(_ : Report) -> False
                  }
                  (CustomTypeGen.run resolvedConfig candidateLookup ct)

        -- Nested under the type's own name so the warning names the type
        -- that failed, not just the inner member/column that triggered it
        -- (CustomType.run itself does not).
        let typeWarningWith =
              \(candidateLookup : CustomKind.Lookup) ->
              \(ct : Model.CustomType) ->
                merge
                  { Ok =
                      \(_ : { value : CustomTypeGen.Output, warnings : List Report }) ->
                        None Report
                  , Err =
                      \(err : Report) -> Some { path = [ ct.name.inSnakeCase ] # err.path, message = err.message }
                  }
                  (CustomTypeGen.run resolvedConfig candidateLookup ct)

        -- Nested custom support requires transitive closure: after one type is
        -- removed, composites depending on it must be reconsidered against the
        -- smaller lookup. Each bounded pass can only remove survivors.
        let effectiveCustomTypes
            : List Model.CustomType
            = if    skip
              then  Natural/fold
                      (Prelude.List.length Model.CustomType input.customTypes)
                      (List Model.CustomType)
                      ( \(survivors : List Model.CustomType) ->
                          let candidateLookup = buildLookup survivors

                          in  Prelude.List.filter
                                Model.CustomType
                                (typeSucceedsWith candidateLookup)
                                survivors
                      )
                      input.customTypes
              else  input.customTypes

        let lookup = buildLookup effectiveCustomTypes

        -- Fail mode: identical to the pre-Skip code (traverseList straight
        -- over input.customTypes), so its error message/path is unchanged.
        let typesForCombine
            : Lude.Compiled.Type (List CustomTypeGen.Output)
            = Lude.Compiled.traverseList
                Model.CustomType
                CustomTypeGen.Output
                ( \(ct : Model.CustomType) ->
                    CustomTypeGen.run resolvedConfig lookup ct
                )
                effectiveCustomTypes

        let queryChecks
            : List QueryCheck
            = Prelude.List.map
                Model.Query
                QueryCheck
                ( \(query : Model.Query) ->
                    merge
                      { Ok =
                          \(_ : { value : QueryGen.Output, warnings : List Report }) ->
                            { query, keep = True, warning = None Report }
                      , Err = \(err : Report) -> { query, keep = False, warning = Some err }
                      }
                      (QueryGen.run resolvedConfig lookup query)
                )
                input.queries

        let effectiveQueries
            : List Model.Query
            = if    skip
              then  Prelude.List.map
                      QueryCheck
                      Model.Query
                      (\(qc : QueryCheck) -> qc.query)
                      (Prelude.List.filter QueryCheck (\(qc : QueryCheck) -> qc.keep) queryChecks)
              else  input.queries

        -- Fail mode: identical to the pre-Skip code (traverseList straight
        -- over input.queries), so its error message/path is unchanged.
        let queriesForCombine
            : Lude.Compiled.Type (List QueryGen.Output)
            = Lude.Compiled.traverseList
                Model.Query
                QueryGen.Output
                ( \(query : Model.Query) ->
                    QueryGen.run resolvedConfig lookup query
                )
                effectiveQueries

        let registrationTypesForCombine
            : Lude.Compiled.Type (List CustomTypeGen.Output)
            = Lude.Compiled.flatMap
                (List CustomTypeGen.Output)
                (List CustomTypeGen.Output)
                registrationOrder
                typesForCombine

        let skipWarnings
            : List Report
            = if    skip
              then    Prelude.List.unpackOptionals
                        Report
                        ( Prelude.List.map
                            Model.CustomType
                            (Optional Report)
                            (typeWarningWith lookup)
                            input.customTypes
                        )
                    # Prelude.List.unpackOptionals
                        Report
                        (Prelude.List.map QueryCheck (Optional Report) (\(qc : QueryCheck) -> qc.warning) queryChecks)
              else  [] : List Report

        let combined
            : Lude.Compiled.Type Output
            = Lude.Compiled.map3
                (List QueryGen.Output)
                (List CustomTypeGen.Output)
                (List CustomTypeGen.Output)
                Output
                (combineOutputs resolvedConfig input)
                queriesForCombine
                typesForCombine
                registrationTypesForCombine

        in  Lude.Compiled.appendWarnings Output skipWarnings combined

in  Sdk.Sigs.interpreter Config Input Output run
