# @generated by python.gen (pGenie). DO NOT EDIT.

from __future__ import annotations

from psycopg import Connection
from psycopg.types import TypeInfo
from psycopg.types.composite import CompositeInfo, register_composite


_COMPOSITE_TYPES = ("public.point2d", "public.tag_value",)
_ENUM_TYPES = ("public.mood",)


def register_types(conn: Connection[object]) -> None:
    for name in _COMPOSITE_TYPES:
        composite_info = CompositeInfo.fetch(conn, name)
        if composite_info is None:
            raise LookupError(f"composite type {name!r} not found; cannot register it")
        register_composite(composite_info, conn)
    for name in _ENUM_TYPES:
        enum_info = TypeInfo.fetch(conn, name)
        if enum_info is None:
            raise LookupError(f"enum type {name!r} not found; cannot register it")
        enum_info.register(conn)
