# @generated by python.gen (pGenie). DO NOT EDIT.
# SPDX-FileCopyrightText: 2026 Viacheslav Shvets
# SPDX-License-Identifier: MIT-0

from __future__ import annotations

from typing import LiteralString, TypeVar

from psycopg import Connection
from psycopg.rows import BaseRowFactory

from .._core import NoRowError

_T = TypeVar("_T")
_Params = dict[str, object]


def fetch_optional(
    conn: Connection[object],
    sql: LiteralString,
    params: _Params,
    row_factory: BaseRowFactory[_T],
) -> _T | None:
    with conn.cursor(row_factory=row_factory) as cur:
        _ = cur.execute(sql, params)
        return cur.fetchone()


def fetch_single(
    conn: Connection[object],
    sql: LiteralString,
    params: _Params,
    row_factory: BaseRowFactory[_T],
) -> _T:
    with conn.cursor(row_factory=row_factory) as cur:
        _ = cur.execute(sql, params)
        row = cur.fetchone()
    if row is None:
        raise NoRowError(sql)
    return row


def fetch_many(
    conn: Connection[object],
    sql: LiteralString,
    params: _Params,
    row_factory: BaseRowFactory[_T],
) -> list[_T]:
    with conn.cursor(row_factory=row_factory) as cur:
        _ = cur.execute(sql, params)
        return cur.fetchall()


def execute_rows_affected(
    conn: Connection[object],
    sql: LiteralString,
    params: _Params,
) -> int:
    with conn.cursor() as cur:
        _ = cur.execute(sql, params)
        return cur.rowcount


def execute_void(
    conn: Connection[object],
    sql: LiteralString,
    params: _Params,
) -> None:
    with conn.cursor() as cur:
        _ = cur.execute(sql, params)
