[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "specimen-sync-client"
version = "0.0.0"
requires-python = ">=3.12"
dependencies = ["psycopg>=3.2"]

[tool.hatch.build.targets.wheel]
packages = ["src/specimen_sync_client"]

[tool.ruff]
exclude = ["src/specimen_sync_client/_generated"]