# @generated by python.gen (pGenie). DO NOT EDIT.
# SPDX-FileCopyrightText: 2026 Viacheslav Shvets
# SPDX-License-Identifier: MIT-0

from __future__ import annotations

from psycopg import Connection

from .._rows import GetSpecimenRow, decode_get_specimen
from .._runtime import fetch_optional

SQL = """\
-- zero_or_one: select by pk with limit 1.
SELECT
  id, pub_id,
  flag, small, medium, large, ratio, precise,
  title, code, letter, born_on, created_at, amount, blob,
  doc_json, doc_jsonb,
  maybe_text, maybe_int, maybe_uuid, maybe_ts, maybe_num,
  tags, related_ids, grid,
  feeling, origin,
  label, rev, meta
FROM specimen
WHERE id = %(id)s
LIMIT 1
"""

_SQL = SQL.encode()


def get_specimen(
    conn: Connection[object],
    *,
    id: int | None,
) -> GetSpecimenRow | None:
    params: dict[str, object] = {
        "id": id,
    }
    return fetch_optional(conn, _SQL, params, decode_get_specimen)
