# @generated by python.gen (pGenie). DO NOT EDIT.
# SPDX-FileCopyrightText: 2026 Viacheslav Shvets
# SPDX-License-Identifier: MIT-0

from __future__ import annotations

from psycopg import Connection

from .._rows import GetTaggedItemRow, decode_get_tagged_item
from .._runtime import fetch_optional

SQL = """\
-- zero_or_one: select by pk with limit 1; the single-field composite here is
-- purely a result column (no parameter use).
SELECT
  id, name, tag
FROM tagged_item
WHERE id = %(id)s
LIMIT 1
"""

_SQL = SQL.encode()


def get_tagged_item(
    conn: Connection[object],
    *,
    id: int | None,
) -> GetTaggedItemRow | None:
    params: dict[str, object] = {
        "id": id,
    }
    return fetch_optional(conn, _SQL, params, decode_get_tagged_item)
