# @generated by python.gen (pGenie). DO NOT EDIT.
# SPDX-FileCopyrightText: 2026 Viacheslav Shvets
# SPDX-License-Identifier: MIT-0

from __future__ import annotations

from collections.abc import Mapping
from dataclasses import dataclass
from datetime import date, datetime
from decimal import Decimal
from typing import cast
from uuid import UUID

from psycopg import Connection

from .._core import JsonValue
from .._runtime import fetch_optional
from ..types.mood import Mood
from ..types.point_2_d import Point2D


@dataclass(frozen=True, slots=True)
class GetSpecimenRow:
    id: int
    pub_id: UUID
    flag: bool
    small: int
    medium: int
    large: int
    ratio: float
    precise: float
    title: str
    code: str
    letter: str
    born_on: date
    created_at: datetime
    amount: Decimal
    blob: bytes
    doc_json: JsonValue
    doc_jsonb: JsonValue
    maybe_text: str | None
    maybe_int: int | None
    maybe_uuid: UUID | None
    maybe_ts: datetime | None
    maybe_num: Decimal | None
    tags: list[str | None]
    related_ids: list[UUID | None] | None
    grid: list[int | None] | None
    feeling: Mood
    origin: Point2D | None
    label: str
    rev: int
    meta: JsonValue


def decode_get_specimen(row: Mapping[str, object]) -> GetSpecimenRow:
    return GetSpecimenRow(
        id=cast(int, row["id"]),
        pub_id=cast(UUID, row["pub_id"]),
        flag=cast(bool, row["flag"]),
        small=cast(int, row["small"]),
        medium=cast(int, row["medium"]),
        large=cast(int, row["large"]),
        ratio=cast(float, row["ratio"]),
        precise=cast(float, row["precise"]),
        title=cast(str, row["title"]),
        code=cast(str, row["code"]),
        letter=cast(str, row["letter"]),
        born_on=cast(date, row["born_on"]),
        created_at=cast(datetime, row["created_at"]),
        amount=cast(Decimal, row["amount"]),
        blob=cast(bytes, row["blob"]),
        doc_json=cast(JsonValue, row["doc_json"]),
        doc_jsonb=cast(JsonValue, row["doc_jsonb"]),
        maybe_text=cast(str | None, row["maybe_text"]),
        maybe_int=cast(int | None, row["maybe_int"]),
        maybe_uuid=cast(UUID | None, row["maybe_uuid"]),
        maybe_ts=cast(datetime | None, row["maybe_ts"]),
        maybe_num=cast(Decimal | None, row["maybe_num"]),
        tags=cast(list[str | None], row["tags"]),
        related_ids=cast(list[UUID | None] | None, row["related_ids"]),
        grid=cast(list[int | None] | None, row["grid"]),
        feeling=Mood.pg_decode(row["feeling"]),
        origin=None if row["origin"] is None else Point2D.pg_decode(row["origin"]),
        label=cast(str, row["label"]),
        rev=cast(int, row["rev"]),
        meta=cast(JsonValue, row["meta"]),
    )


SQL = """\
-- zero_or_one: select by pk with limit 1.
SELECT
  id, pub_id,
  flag, small, medium, large, ratio, precise,
  title, code, letter, born_on, created_at, amount, blob,
  doc_json, doc_jsonb,
  maybe_text, maybe_int, maybe_uuid, maybe_ts, maybe_num,
  tags, related_ids, grid,
  feeling, origin,
  label, rev, meta
FROM specimen
WHERE id = %(id)s
LIMIT 1
"""

_SQL = SQL.encode()


def get_specimen(
    conn: Connection[object],
    *,
    id: int | None,
) -> GetSpecimenRow | None:
    params: dict[str, object] = {
        "id": id,
    }
    return fetch_optional(conn, _SQL, params, decode_get_specimen)
