# @generated by python.gen (pGenie). DO NOT EDIT.
# SPDX-FileCopyrightText: 2026 Viacheslav Shvets
# SPDX-License-Identifier: MIT-0

from __future__ import annotations

from collections.abc import Mapping
from dataclasses import dataclass
from typing import cast as _cast

from psycopg import Connection

from .._runtime import fetch_single as _fetch_single
from ..types.tag_value import TagValue


@dataclass(frozen=True, slots=True)
class InsertTaggedItemRow:
    id: int
    name: str
    tag: TagValue


def _decode_row(row: Mapping[str, object]) -> InsertTaggedItemRow:
    return InsertTaggedItemRow(
        id=_cast(int, row["id"]),
        name=_cast(str, row["name"]),
        tag=TagValue.pg_decode(row["tag"]),
    )


SQL = """\
-- single row: insert exercising a single-field composite as a parameter and
-- (via RETURNING) as a result column, in the same statement.
INSERT INTO tagged_item (name, tag)
VALUES (%(name)s, %(tag)s)
RETURNING id, name, tag
"""

_SQL = SQL.encode()


def insert_tagged_item(
    conn: Connection[object],
    *,
    name: str,
    tag: TagValue,
) -> InsertTaggedItemRow:
    params: dict[str, object] = {
        "name": name,
        "tag": tag.pg_encode(),
    }
    return _fetch_single(conn, _SQL, params, _decode_row)
