# @generated by python.gen (pGenie). DO NOT EDIT.
# SPDX-FileCopyrightText: 2026 Viacheslav Shvets
# SPDX-License-Identifier: MIT-0

from __future__ import annotations

from collections.abc import Mapping
from dataclasses import dataclass
from typing import cast as _cast

from psycopg import Connection

from .._runtime import fetch_many as _fetch_many


@dataclass(frozen=True, slots=True)
class ListSpecimensKeywordColumnRow:
    id: int
    class_: str


def _decode_row(row: Mapping[str, object]) -> ListSpecimensKeywordColumnRow:
    return ListSpecimensKeywordColumnRow(
        id=_cast(int, row["id"]),
        class_=_cast(str, row["class"]),
    )


SQL = """\
-- Keyword result-column coverage: the column aliased to the reserved word class
-- must emit a dataclass field and decode kwarg of class_ while the row lookup
-- keeps the raw \"class\". Without sanitization the generated _rows.py has a
-- SyntaxError, so this query locks the result-column guard (mirrors
-- list_specimens_by_class for params).
SELECT
  id,
  title AS \"class\"
FROM specimen
ORDER BY id ASC
"""

_SQL = SQL.encode()


def list_specimens_keyword_column(
    conn: Connection[object],
) -> list[ListSpecimensKeywordColumnRow]:
    params: dict[str, object] = {}
    return _fetch_many(conn, _SQL, params, _decode_row)
