# @generated by python.gen (pGenie). DO NOT EDIT.
# SPDX-FileCopyrightText: 2026 Viacheslav Shvets
# SPDX-License-Identifier: MIT-0

from __future__ import annotations

from collections.abc import Mapping
from dataclasses import dataclass
from typing import cast

from psycopg import Connection
from psycopg.types.json import Jsonb

from .._core import JsonValue
from .._runtime import fetch_many


@dataclass(frozen=True, slots=True)
class SearchSpecimensRow:
    id: int
    title: str
    label: str
    meta: JsonValue


def decode_search_specimens(row: Mapping[str, object]) -> SearchSpecimensRow:
    return SearchSpecimensRow(
        id=cast(int, row["id"]),
        title=cast(str, row["title"]),
        label=cast(str, row["label"]),
        meta=cast(JsonValue, row["meta"]),
    )


SQL = """\
-- many: nullable parameter via coalesce, jsonb containment parameter, and a
-- domain comparison with the param cast to the base type (pgn cannot bind a
-- domain parameter directly).
SELECT
  id, title, label, meta
FROM specimen
WHERE
  title ILIKE COALESCE(%(title_like)s, '%%')
  AND meta @> %(meta_filter)s::jsonb
  AND label = COALESCE(%(label)s::text, label)
ORDER BY id ASC
"""

_SQL = SQL.encode()


def search_specimens(
    conn: Connection[object],
    *,
    title_like: str | None,
    meta_filter: JsonValue | None,
    label: str | None,
) -> list[SearchSpecimensRow]:
    params: dict[str, object] = {
        "title_like": title_like,
        "meta_filter": None if meta_filter is None else Jsonb(meta_filter),
        "label": label,
    }
    return fetch_many(conn, _SQL, params, decode_search_specimens)
