# @generated by python.gen (pGenie); regeneration overwrites manual changes.
# SPDX-FileCopyrightText: 2026 Viacheslav Shvets
# SPDX-License-Identifier: MIT-0

"""Generated database client for specimen-client."""

__all__: list[str] = []
