# @generated by python.gen (pGenie); regeneration overwrites manual changes.
# SPDX-FileCopyrightText: 2026 Viacheslav Shvets
# SPDX-License-Identifier: MIT-0

from __future__ import annotations

import keyword
from collections.abc import Callable, Sequence
from dataclasses import fields, is_dataclass
from typing import Any

from psycopg import AsyncConnection, Connection
from psycopg.types.composite import CompositeInfo, register_composite
from psycopg.types.enum import EnumInfo, register_enum

from . import types as _db_types

type _ObjectMaker[T] = Callable[[Sequence[Any], CompositeInfo], T]
type _SequenceMaker[T] = Callable[[T, CompositeInfo], Sequence[Any]]


def _python_name(name: str) -> str:
    if keyword.iskeyword(name):
        return f"{name}_"
    return name


def _dataclass_callbacks[T](cls: type[T]) -> tuple[_ObjectMaker[T], _SequenceMaker[T]]:
    if not is_dataclass(cls):
        raise TypeError(f"{cls.__name__} must be a dataclass")

    model_fields = fields(cls)
    model_names = tuple(field.name for field in model_fields)

    def make_object(values: Sequence[Any], info: CompositeInfo) -> T:
        names = tuple(_python_name(name) for name in info.field_names)
        assert names == model_names
        assert len(values) == len(model_fields)
        return cls(**dict(zip(names, values, strict=True)))

    def make_sequence(obj: T, info: CompositeInfo) -> Sequence[Any]:
        names = tuple(_python_name(name) for name in info.field_names)
        assert names == model_names
        return tuple(getattr(obj, field.name) for field in model_fields)

    return make_object, make_sequence


_mood_pg_name = "public.mood"
_point_2_d_pg_name = "public.point2d"
_point_2_d_make_object, _point_2_d_make_sequence = _dataclass_callbacks(_db_types.Point2D)
_tag_value_pg_name = "public.tag_value"
_tag_value_make_object, _tag_value_make_sequence = _dataclass_callbacks(_db_types.TagValue)
_z_codec_payload_pg_name = "public.z_codec_payload"
_z_codec_payload_make_object, _z_codec_payload_make_sequence = _dataclass_callbacks(_db_types.ZCodecPayload)
_a_codec_wrapper_pg_name = "public.a_codec_wrapper"
_a_codec_wrapper_make_object, _a_codec_wrapper_make_sequence = _dataclass_callbacks(_db_types.ACodecWrapper)


async def register_types(conn: AsyncConnection[object]) -> None:
    mood_info = await EnumInfo.fetch(conn, _mood_pg_name)
    if mood_info is None:
        raise LookupError(f"enum type {_mood_pg_name!r} not found; cannot register it")
    register_enum(
        mood_info,
        conn,
        _db_types.Mood,
        mapping={member: member.value for member in _db_types.Mood},
    )
    point_2_d_info = await CompositeInfo.fetch(conn, _point_2_d_pg_name)
    if point_2_d_info is None:
        raise LookupError(f"composite type {_point_2_d_pg_name!r} not found; cannot register it")
    register_composite(
        point_2_d_info,
        conn,
        _db_types.Point2D,
        make_object=_point_2_d_make_object,
        make_sequence=_point_2_d_make_sequence,
    )
    tag_value_info = await CompositeInfo.fetch(conn, _tag_value_pg_name)
    if tag_value_info is None:
        raise LookupError(f"composite type {_tag_value_pg_name!r} not found; cannot register it")
    register_composite(
        tag_value_info,
        conn,
        _db_types.TagValue,
        make_object=_tag_value_make_object,
        make_sequence=_tag_value_make_sequence,
    )
    z_codec_payload_info = await CompositeInfo.fetch(conn, _z_codec_payload_pg_name)
    if z_codec_payload_info is None:
        raise LookupError(f"composite type {_z_codec_payload_pg_name!r} not found; cannot register it")
    register_composite(
        z_codec_payload_info,
        conn,
        _db_types.ZCodecPayload,
        make_object=_z_codec_payload_make_object,
        make_sequence=_z_codec_payload_make_sequence,
    )
    a_codec_wrapper_info = await CompositeInfo.fetch(conn, _a_codec_wrapper_pg_name)
    if a_codec_wrapper_info is None:
        raise LookupError(f"composite type {_a_codec_wrapper_pg_name!r} not found; cannot register it")
    register_composite(
        a_codec_wrapper_info,
        conn,
        _db_types.ACodecWrapper,
        make_object=_a_codec_wrapper_make_object,
        make_sequence=_a_codec_wrapper_make_sequence,
    )


def register_types_sync(conn: Connection[object]) -> None:
    mood_info = EnumInfo.fetch(conn, _mood_pg_name)
    if mood_info is None:
        raise LookupError(f"enum type {_mood_pg_name!r} not found; cannot register it")
    register_enum(
        mood_info,
        conn,
        _db_types.Mood,
        mapping={member: member.value for member in _db_types.Mood},
    )
    point_2_d_info = CompositeInfo.fetch(conn, _point_2_d_pg_name)
    if point_2_d_info is None:
        raise LookupError(f"composite type {_point_2_d_pg_name!r} not found; cannot register it")
    register_composite(
        point_2_d_info,
        conn,
        _db_types.Point2D,
        make_object=_point_2_d_make_object,
        make_sequence=_point_2_d_make_sequence,
    )
    tag_value_info = CompositeInfo.fetch(conn, _tag_value_pg_name)
    if tag_value_info is None:
        raise LookupError(f"composite type {_tag_value_pg_name!r} not found; cannot register it")
    register_composite(
        tag_value_info,
        conn,
        _db_types.TagValue,
        make_object=_tag_value_make_object,
        make_sequence=_tag_value_make_sequence,
    )
    z_codec_payload_info = CompositeInfo.fetch(conn, _z_codec_payload_pg_name)
    if z_codec_payload_info is None:
        raise LookupError(f"composite type {_z_codec_payload_pg_name!r} not found; cannot register it")
    register_composite(
        z_codec_payload_info,
        conn,
        _db_types.ZCodecPayload,
        make_object=_z_codec_payload_make_object,
        make_sequence=_z_codec_payload_make_sequence,
    )
    a_codec_wrapper_info = CompositeInfo.fetch(conn, _a_codec_wrapper_pg_name)
    if a_codec_wrapper_info is None:
        raise LookupError(f"composite type {_a_codec_wrapper_pg_name!r} not found; cannot register it")
    register_composite(
        a_codec_wrapper_info,
        conn,
        _db_types.ACodecWrapper,
        make_object=_a_codec_wrapper_make_object,
        make_sequence=_a_codec_wrapper_make_sequence,
    )
