# @generated by python.gen (pGenie). DO NOT EDIT.
# SPDX-FileCopyrightText: 2026 Viacheslav Shvets
# SPDX-License-Identifier: MIT-0

from __future__ import annotations

from typing import LiteralString, TypeVar

from psycopg import AsyncConnection
from psycopg.rows import BaseRowFactory

from ._core import NoRowError

_T = TypeVar("_T")
_Params = dict[str, object]


async def fetch_optional(
    conn: AsyncConnection[object],
    sql: LiteralString,
    params: _Params,
    row_factory: BaseRowFactory[_T],
) -> _T | None:
    async with conn.cursor(row_factory=row_factory) as cur:
        _ = await cur.execute(sql, params)
        return await cur.fetchone()


async def fetch_single(
    conn: AsyncConnection[object],
    sql: LiteralString,
    params: _Params,
    row_factory: BaseRowFactory[_T],
) -> _T:
    async with conn.cursor(row_factory=row_factory) as cur:
        _ = await cur.execute(sql, params)
        row = await cur.fetchone()
    if row is None:
        raise NoRowError(sql)
    return row


async def fetch_many(
    conn: AsyncConnection[object],
    sql: LiteralString,
    params: _Params,
    row_factory: BaseRowFactory[_T],
) -> list[_T]:
    async with conn.cursor(row_factory=row_factory) as cur:
        _ = await cur.execute(sql, params)
        return await cur.fetchall()


async def execute_rows_affected(
    conn: AsyncConnection[object],
    sql: LiteralString,
    params: _Params,
) -> int:
    async with conn.cursor() as cur:
        _ = await cur.execute(sql, params)
        return cur.rowcount


async def execute_void(
    conn: AsyncConnection[object],
    sql: LiteralString,
    params: _Params,
) -> None:
    async with conn.cursor() as cur:
        _ = await cur.execute(sql, params)
